### ISSUE TITLE
callrb corrupt file

### ISSUE THREAD

**Issue by pachamaltese** [r-lib/callr#102]
just trying to update r4ds spanish version I get:

```r
Error in get0(oNam, envir = ns) : 
  lazy-load database '/home/pacha/R/x86_64-pc-linux-gnu-library/3.5/callr/R/callr.rdb' is corrupt
In addition: Warning message:
In get0(oNam, envir = ns) : internal error -3 in R_decompress1
```

a bit of context, the script that builds the book via travis does `devtools::install_github("cienciadedatos/r4ds")` and at the installation step it fails just when installing `callr` which a dependency of `httpuv`

**Comment by gaborcsardi** [comment]
This is a base R bug and it happens when you update a package that is loaded. Restart R, and it should be fine, assuming the installation itself was OK.

**Comment by raynamharris** [comment]
thanks! I got the same error message and restarting R worked for me.
