### ISSUE TITLE
callr::r() returns pointers of keras objects

### ISSUE THREAD

**Issue by Lauler** [r-lib/callr#118]
I'm trying to use `callr::r()` inside of a `map`-function in order to fit keras models on CV splits of my data. The reason is to force the release of GPU memory by killing the python interpreter between each call. At the end of the function I'd like to return the model.

The function however only returns a pointer. And I don't really know what to do with that pointer.

Minimal reproducible example (that doesn't fit anything):

```
library(tibble)
library(callr)
library(keras)

list_of_dfs <- list(tibble(value = 2),
                    tibble(value = 4),
                    tibble(value = 5))

example_fun <- function(df_train, extra_fun, extra_arg, ...){
  `%>%` <- keras::`%>%`
  
  conv_base <- extra_fun()
  
  model <- keras::keras_model_sequential() %>%
    conv_base %>%
    keras::layer_dense(units = 1)
  
  model %>% keras::compile(
    loss = "mse",
    optimizer = keras::optimizer_adam(lr = 1e-4),
    metrics = "mse"
  )
  
  return(list(model, extra_arg))
}
  
res <- purrr::map(
  .x = list_of_dfs,
  .f = function(df, my_fun, ...){
    
    r(func = my_fun,
      args = list(
        df_train = df,
        ...
      ),
      show = TRUE
    )
  },
  my_fun = example_fun,
  extra_fun = function(){keras::application_resnet50(include_top = FALSE,
                                          input_shape = c(224, 224, 3))},
  extra_arg = 1)
```

The output is:

```
> res
[[1]]
[[1]][[1]]
<pointer: 0x0>

[[1]][[2]]
[1] 1


[[2]]
[[2]][[1]]
<pointer: 0x0>

[[2]][[2]]
[1] 1


[[3]]
[[3]][[1]]
<pointer: 0x0>

[[3]][[2]]
[1] 1
```
Checking the type of the pointer:

```
> res[[1]][[1]]
<pointer: 0x0>
> typeof(res[[1]][[1]])
[1] "closure"
> class(res[[1]][[1]])
[1] "keras.engine.sequential.Sequential"                        
[2] "keras.engine.training.Model"                               
[3] "keras.engine.network.Network"                              
[4] "keras.engine.base_layer.Layer"                             
[5] "tensorflow.python.module.module.Module"                    
[6] "tensorflow.python.training.tracking.tracking.AutoTrackable"
[7] "tensorflow.python.training.tracking.base.Trackable"        
[8] "python.builtin.object" 
```

Why does it return a pointer and is there a way that I can actually use these pointers?

**Comment by gaborcsardi** [comment]
You cannot copy external pointers between processes. Maybe there is a way to convert the keras object to something that can be `save()`-d, please ask at the keras repo: https://github.com/rstudio/keras/issues

**Comment by dfalbel** [comment]
Persisting TF models is tricky. You can use the `keras::serialize_model` by modifying your `example_fun` to return something like this:

`return(list(keras::serialize_model(model), extra_arg))`

You can then get  the models from the `res` object with:

`models <- purrr::map(res, ~keras::unserialize_model(.x[[1]]))`

If you have more complicated models I recommend serializing to disk using the Saved Model format. You can see more info here: https://tensorflow.rstudio.com/keras/articles/saving_serializing.html
