### ISSUE TITLE
callr 3.3.0 and 3.3.0.9000 crash, but not 3.2.0

### ISSUE THREAD

**Issue by jdblischak** [r-lib/callr#121]
Versions 3.3.0 and 3.3.0.9000 of callr are causing my unit tests to fail, but I don't yet understand why. I repeatedly get the following error:

```
callr subprocess failed: could not start R, exited with non-zero status, has crashed or was killed
```

callr 3.2.0 continues to work fine. I've tested it locally, and also my [CI build that uses an older rocker image](https://circleci.com/gh/jdblischak/workflowr/597) (and thus MRAN is pinned to an older date) continues to pass since it is using callr 3.2.0.

In contrast, if I install callr 3.3.0 or 3.3.0.9000 (i.e. current GitHub master), the unit tests fail locally and also for my CI builds on [Linux](https://circleci.com/gh/jdblischak/workflowr/600), [macOS](https://travis-ci.org/jdblischak/workflowr/builds/560554039#L891), and [Windows](https://ci.appveyor.com/project/jdblischak/workflowr/builds/26079397#L454).

But the reason I haven't been able to diagnose the exact problem is because when I run the same code manually (i.e. not via testthat), there are no errors.

I'll continue investigating, but I'd appreciate any insight. Thanks!

**Comment by jdblischak** [comment]
The errors also aren't deterministic.

Occasionally this test file will pass:

```
devtools::test(filter = "build$")
```

But this one always fails:

```
devtools::test(filter = "report$")
```

And once the above fails, then the tests in `filter = "build$"` start to fail.

The above observations were made in RStudio. When I try to reproduce this in the terminal, they always fail:

```
git clone git@github.com:jdblischak/workflowr.git /tmp/workflowr
Rscript -e 'devtools::test("/tmp/workflowr", filter = "build$")'
Rscript -e 'devtools::test("/tmp/workflowr", filter = "report$")'
Rscript -e 'devtools::test("/tmp/workflowr", filter = "build$")'
```

Confusingly though, when I test only the function that actually calls `callr::r_safe()`, it always works:

```
Rscript -e 'devtools::test("/tmp/workflowr", filter = "build_rmd_external$")'
```

**Comment by jdblischak** [comment]
The main problem seems to be in [test-report.R](https://github.com/jdblischak/workflowr/blob/master/tests/testthat/test-report.R). If I delete that test file, then all the others run without error. When I include *only* that test file, sometimes it fails and sometimes not.

**Comment by gaborcsardi** [comment]
That's quite a big file, can you try to narrow it down even more? I suspect that it is a race condition, e.g. with a finalizer.

**Comment by jdblischak** [comment]
Yes, I'm working on creating a smaller test package that reproduces the error.

**Comment by jdblischak** [comment]
I've put together a smaller example in the repo [callrTest](https://github.com/jdblischak/callrTest).

The tests [pass](https://travis-ci.org/jdblischak/callrTest/jobs/561188135) with callr 3.2.0.

The tests [fail](https://travis-ci.org/jdblischak/callrTest/jobs/561188136) with callr 3.3.0.9000.

There are 3 test files:

* [test-fx.R](https://github.com/jdblischak/callrTest/blob/master/tests/testthat/test-fx.R) - This tests a minimal function that uses callr to render an R Markdown file. It passes.
* [test-report.R](https://github.com/jdblischak/callrTest/blob/master/tests/testthat/test-report.R) - This is a subsection of the original test file from my workflowr package. It always triggers an error.
* [test-z-fx-2](https://github.com/jdblischak/callrTest/blob/master/tests/testthat/test-z-fx-2.R) - It contains exactly the same test as `test-fx.R`. However, since it is run after an earlier callr failure, it fails.

**Comment by jdblischak** [comment]
I think I may have found the problem. One of my unit tests was accidentally deleting the R session's temporary directory. Was there a change introduced between callr 3.2.0 and 3.3.0 that would be affected by a missing session directory? Maybe this [line](https://github.com/r-lib/callr/compare/v3.2.0...v3.3.0#diff-951791f1fb37d9e5b0f0cf852ce38d83R58) that saves an environment into to an RDS file in the temporary directory?

**Comment by gaborcsardi** [comment]
Yes, that is indeed the casr.
