### ISSUE TITLE
Updating the callr package gives Rd warning:

### ISSUE THREAD

**Issue by anthonyj2k20** [r-lib/callr#122]
Updating the callr package gives Rd warning today as follows:
Rd warning: C:/Users/anthj/AppData/Local/Temp/Rtmp0gVSJc/R.INSTALL31742030316c/callr/man/r.Rd:146: file link 'dump.frames' in package 'utils' does not exist and so has been treated as a topic

**Comment by gaborcsardi** [comment]
This is harmless, you can ignore it.

**Comment by jennybc** [comment]
@anthonyj2k20 For a longer discussion that also conveys "this is harmless, you can ignore it" see https://github.com/klutometis/roxygen/issues/707, if you want more detail.
