### ISSUE TITLE
Question: How to pass environment variables

### ISSUE THREAD

**Issue by HalfEatenPie** [r-lib/callr#126]
I've looked at a few of the other issues related to this but I can't seem to wrap my head around it.

I'm interested in passing environment variables I've set in the global environment into the environment that I'm running a function or a script in.

Specifically, the example is:

```
callr::rscript('path/to/R/script.R', wd = 'path/to')
```

I saw the rscript function accepts `env`, however by default it uses `rcmd_safe_env()`. 

Do I add my environment variable there?  How do I pass through lets say `no_cores` to the `callr::rscript` function?

Thanks.

**Comment by gaborcsardi** [comment]
This is how to pass an environment variable:

```r
sc <- tempfile()
cat("Sys.getenv('FOOBAR')\n", file = sc)
callr::rscript(sc, env = c(callr::rcmd_safe_env(), FOOBAR = "hello"))
#> [1] "hello"
```

I am not sure what you mean by global environment, maybe you want to pass R variables instead of environment variables?

**Comment by HalfEatenPie** [comment]
This is perfect thanks!  Yeah my phrasing could have been better but this is exactly it.

**Comment by gaborcsardi** [comment]
`env` is not for R variables, but environment variables. You can only pass R variables as function arguments.

**Comment by roumail** [comment]
So I guess I just convert my R variables into an environment variable to make it work. Thanks for the quick answer!

**Comment by gaborcsardi** [comment]
Here is passing a data frame:

```r
opts <- callr::r_process_options(
  func = function(input) summary(input),
  args = list(input = mtcars)
)
rp <- callr::r_process$new(opts)
rp$wait()
rp$get_result()
```
