### ISSUE TITLE
use magrittr pipe inside function?

### ISSUE THREAD

**Issue by anthonyatto** [r-lib/callr#127]
is it possible to use the magrittr pipe operator inside a callr function? 
for example: 
`r(function() {mtcars magrittr::'%>%' dplyr::filter(cyl == 4)})` does not work, but neither does `mtcars magrittr::'%>%' dplyr::filter(cyl == 4)}`. 
thanks to the developers and maintainers.

**Comment by gaborcsardi** [comment]
You need to load magrittr in the subprocess, i.e. put `library(magrittr)` at the beginning of your function.
