### ISSUE TITLE
r_bg() fails to run when executing script via Rscript

### ISSUE THREAD

**Issue by leungi** [r-lib/callr#128]
Reprex below.

__Using callr::r()__
This returns `.csv` as expected.
```r
$ Rscript --verbose -e "callr::r(function(x) {Sys.sleep(2); write.csv(head(iris, 2), '/home/leungi/test.csv')})"
running
  '/usr/lib64/R/bin/R --slave --no-restore -e callr::r(function(x) {Sys.sleep(2); write.csv(head(iris, 2), '/home/leungi/test.csv')})'

NULL
```

__Using callr::r_bg()__
This doesn't output `.csv` even though message indicates process kicked off.
```r
$ Rscript --verbose -e "callr::r_bg(function(x) {Sys.sleep(2); write.csv(head(iris, 2), '/home/leungi/test.csv')})"
running
  '/usr/lib64/R/bin/R --slave --no-restore -e callr::r_bg(function(x) {Sys.sleep(2); write.csv(head(iris, 2), '/home/leungi/test.csv')})'

PROCESS 'R', running, pid 54762.
```

__System Info__
```
$ uname -a
Linux vm2-d 3.10.0-514.el7.x86_64 #1 SMP Wed Oct 19 11:24:13 EDT 2016 x86_64 x86_64 x86_64 GNU/Linux

```

**Comment by gaborcsardi** [comment]
Because the process is killed automatically when its starting R process exits.

**Comment by gaborcsardi** [comment]
What are you trying to achieve?

**Comment by leungi** [comment]
Thanks for prompt response @gaborcsardi!

I'm trying to schedule (via `.sh` script) multiple R scripts (e.g., 01_.R, 02_.R), with the subsequent script dependent on the full execution of the preceding script (i.e., 02_.R will not kick off until 01_.R...and all its background sessions...completes).

I'm using `callr` in 01_.R to achieve a poorboy parallelization.

**Comment by gaborcsardi** [comment]
Then in the script, you need to wait for the bg sessions to complete. E.g.

```r
## start all bg sessions
s1 <- callr::r_bg(function() Sys.sleep(5))
s2 <- callr::r_bg(function() Sys.sleep(4))
s3 <- callr::r_bg(function() Sys.sleep(7))

## wait for all of them to complete
s1$wait()
s2$wait()
s3$wait()
```

**Comment by leungi** [comment]
`wait()` the key to success, as in real life 😁

Appreciate the quick help @gaborcsardi!
