### ISSUE TITLE
`callr::r` should be using the current `.libPaths()` exclusively in `packrat` environment.

### ISSUE THREAD

**Issue by randy3k** [r-lib/callr#131]
`callr::r` should be using the current `.libPaths()` exclusively in `packrat` environment and do not append the system library.

```r
Packrat mode on. Using library in directory:
- "~/Desktop/foo/packrat/lib"
.R version 3.6.1 (2019-07-05) -- "Action of the Toes"
Platform: x86_64-apple-darwin15.6.0 (64-bit)

r$> .libPaths()
[1] "/Users/Randy/Desktop/foo/packrat/lib/x86_64-apple-darwin15.6.0/3.6.1"
[2] "/Users/Randy/Desktop/foo/packrat/lib-ext/x86_64-apple-darwin15.6.0/3.6.1"
[3] "/Users/Randy/Desktop/foo/packrat/lib-R/x86_64-apple-darwin15.6.0/3.6.1"

r$> callr::r(function() .libPaths())
[1] "/Users/Randy/Desktop/foo/packrat/lib/x86_64-apple-darwin15.6.0/3.6.1"
[2] "/Users/Randy/Desktop/foo/packrat/lib-ext/x86_64-apple-darwin15.6.0/3.6.1"
[3] "/Users/Randy/Desktop/foo/packrat/lib-R/x86_64-apple-darwin15.6.0/3.6.1"
[4] "/Library/Frameworks/R.framework/Versions/3.6/Resources/library"
```

how to reproduce:

1. cd to an empty directory
2. `packrat::init()`
3. `.libPaths()` -> doesn't contain the system library
4. `callr::r(function() .libPaths())` contains the system library

**Comment by gaborcsardi** [comment]
This is caused by our custom environment files and profiles. If I do 
```R
#    if (is.na(env["R_ENVIRON"])) env["R_ENVIRON"] <- envs[[1]]
#    if (is.na(env["R_ENVIRON_USER"])) env["R_ENVIRON_USER"] <- envs[[2]]
    if (is.na(env["R_PROFILE"])) env["R_PROFILE"] <- profiles[[1]]
#    if (is.na(env["R_PROFILE_USER"])) env["R_PROFILE_USER"] <- profiles[[2]]
```
then it works as it should.

I am not sure why it happens, though, because we never explicitly use `.Library` anywhere, only `.libPaths()`.

**Comment by gaborcsardi** [comment]
OK, I am not sure if this is a bug, actually. callr does not load the user profile by default, so packrat's `.Rprofile` is not loaded. This means the packrat has no chance to remove the system library that R includes automatically. If you do 

```r
callr::r(function() .libPaths(), user_profile = TRUE)
```

then you get the expected output. Omitting the system library is kind of a hack, and callr could do the same, i.e. remove if in the subprocess if the main process does not have it, but I am not sure if it is worth it.

Does the current behavior cause any problems for you in practice?

**Comment by randy3k** [comment]
I think it makes sense for the child process to inherit exactly the same `.libPaths` for reproducibility. I once had a hard time to debug some code run in `callr` because it was calling a package which was not installed in the `packrat` environment but in the system environment.

The purpose of `packrat` is to create a sandbox environment and failing to keep the same `.libPaths` defects the purpose of `packrat`.

**Comment by gaborcsardi** [comment]
The problem is that you cannot easily remove the system library. packrat does some trick to do it.

If you mix packrat and callr, then you always need `user_profile = TRUE`, otherwise packrat is not loaded in the child process. The callr default is `user_profile = FALSE`.

**Comment by randy3k** [comment]
It is not a problem for R scripts. 

But for package developers, if they want to use `callr` in their packages, they will need to check if `packrat` is used and call the corresponding commands correspondingly.

```
if (packrat_mode_on()) {
	callr::r(....., user_profile = True)
} else {
	callr::r(.....)
}
```
It creates an additional level of maintenance.

**Comment by gaborcsardi** [comment]
Right. I am just not sure what callr could do here, really. I can try to copy packrat's trick to remove the system library, but that's just one thing. The real issue is that packrat is not loaded in the subprocess, so its shims are not active, etc.

**Comment by gaborcsardi** [comment]
@kevinushey should callr load the `.Rprofile` automatically in a packrat project? Does the packrat .Rprofile also load the user's R profile? 

I am really not sure what the right solution is here.

**Comment by randy3k** [comment]
> Does the packrat .Rprofile also load the user's R profile.

I don’t think so.

**Comment by kevinushey** [comment]
All of the Packrat magic happens through sourcing the project's `.Rprofile` (including its override of the system library paths) so I believe the simplest fix would be for `callr` to source the project `.Rprofile` in such a case.

IMHO, if a `.Rprofile` exists within the working directory of the process launched by `callr`, it should be sourced by default.

Packrat indeed does not source the user profile by default.

**Comment by gaborcsardi** [comment]
> IMHO, if a .Rprofile exists within the working directory of the process launched by callr, it should be sourced by default.

That is a breaking change, though, and frankly I am not sure if it is worth it. callr could also recognize packrat projects and source their profiles. That does not seem right, either, but maybe the easiest solution here.

> Packrat indeed does not source the user profile by default.

Shouldn't it, though? The user's profile is for setup that applies to all R projects. So why not source it?

**Comment by kevinushey** [comment]
> Shouldn't it, though? The user's profile is for setup that applies to all R projects. So why not source it?

Some arguments against:

1. If you have a project local `.Rprofile`, then the global `.Rprofile` is not sourced by default. So perhaps one should aim to conform to the 'default' R behavior.

2. Packrat and renv generally try to isolate projects, but a user profile might choose settings or load packages which one normally doesn't want for a particular project.

Ultimately I believe it comes down to user preference and so the onus is on the user to ask renv or Packrat to source the user profile if so desired.

**Comment by gaborcsardi** [comment]
> If you have a project local .Rprofile, then the global .Rprofile is not sourced by default. So perhaps one should aim to conform to the 'default' R behavior.

Well, it is not really the user's choice though, packrat forces the local .Rprofile on the user.

> Packrat and renv generally try to isolate projects, but a user profile might choose settings or load packages which one normally doesn't want for a particular project.

It might. It kind of also makes sense to put the stuff the you want for _all_ of your projects into the user profile.

> Ultimately I believe it comes down to user preference and so the onus is on the user to ask renv or Packrat to source the user profile if so desired.

How would they do so? Is it OK to edit the profile? (Leaving the packrat part intact of course.)

**Comment by kevinushey** [comment]
It is indeed okay to edit the project profile and add your own stuff around the Packrat / renv autoloaders. `renv` also has an option that users can set to control whether it attempts to source the user profile (and it does so after it's set up its private library paths and other project state). Activating or deactivating a project amounts to commenting out the auto-loader part of the code.

Ultimately, some users will want the user profile to be sourced and others will not, so I think it's the responsibility of Packrat / renv / the maintainer of the project `.Rprofile` to control whether the user profile is sourced.

Absent any explicit decision from the user, I think it's okay to conform to the default R behavior, especially because some user profiles may cause issues when sourced within a Packrat / renv project.
