### ISSUE TITLE
callr subprocess failed: could not start R, exited with non-zero status, has crashed or was killed>

### ISSUE THREAD

**Issue by carloscinelli** [r-lib/callr#140]
When using `callr` with the latest RStudio and latest R, I get the following error:

```
callr::r_safe(function()ls())

Error: <callr_status_error in get_result(output = out, options):
 callr subprocess failed: could not start R, exited with non-zero status, has crashed or was killed>

See `.Last.error.trace` for a stack trace.
```

This is what `.Last.error.trace` shows:

```
Stack trace:

 1. callr::r_safe(function() ls())
 2. callr:::get_result(output = out, options)
 3. throw(new_callr_error(output, killmsg))

 x callr subprocess failed: could not start R, exited with non-zero status, has crashed or was killed 
```

This problem does not happen when using vanilla R without RStudio.

Here is my session info:

```
R version 3.6.2 (2019-12-12)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Catalina 10.15.2

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.6/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] callr_3.4.0

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.3        rstudioapi_0.10   magrittr_1.5      usethis_1.5.1     devtools_2.2.1    pkgload_1.0.2     R6_2.4.1         
 [8] rlang_0.4.2       fansi_0.4.1       tools_3.6.2       pkgbuild_1.0.6    sessioninfo_1.1.1 cli_2.0.1         withr_2.1.2      
[15] ellipsis_0.3.0    remotes_2.1.0     assertthat_0.2.1  digest_0.6.23     rprojroot_1.3-2   crayon_1.3.4      processx_3.4.1   
[22] fs_1.3.1          ps_1.3.0          curl_4.3          testthat_2.3.1    memoise_1.1.0     glue_1.3.1        compiler_3.6.2   
[29] desc_1.2.0        backports_1.1.5   prettyunits_1.1.0
```

**Comment by gaborcsardi** [comment]
This works fine for me in a recent RStudio (Version 1.3.652), so we would need some more info.

**Comment by carloscinelli** [comment]
Just tell me what info you need.

**Comment by carloscinelli** [comment]
I using Version 1.2.5033

**Comment by gaborcsardi** [comment]
Does `system("R --vanilla -e 'ls()'"` work?

What is the RStudio version number?

Have you used this on another macOS version?

**Comment by carloscinelli** [comment]
`system("R --vanilla -q -e 'ls()'")` works fine, below: 
`system("R --vanilla -q -e 'ls()'")
> ls()
character(0)
> 
> `

I using RStudio Version 1.2.5033.

Didn't try in another macOS version.

**Comment by carloscinelli** [comment]
This is certainly an RStudio bug. I have tried re-installing RStudio and it didn't work, I think I will try downgrading. There are problems happening with other packages as well,  see here: https://github.com/r-lib/devtools/issues/2178

**Comment by gaborcsardi** [comment]
Ah, that's probably a typo in an `.Rprofile` file of yours.

**Comment by gaborcsardi** [comment]
Maybe you are missing a trailing newline at the end of `.Rprofile`?

**Comment by carloscinelli** [comment]
My `.Rprofile` (accessed with `usethis::edit_r_profile()`) is empty (nothing there). Should I check in another place as well?

**Comment by gaborcsardi** [comment]
The `options(repos="http://cran.us.r-project.org")` code in your devtools issue seems to come from a profile, user or system.

**Comment by gaborcsardi** [comment]
I would be surprised if it was coming from RStudio. Do you have an `.Rprofile` file in your project?

**Comment by gaborcsardi** [comment]
Is your project on GitHub, or can you share it?

**Comment by carloscinelli** [comment]
Yeah, one example project is this: https://github.com/chadhazlett/sensemakr

**Comment by carloscinelli** [comment]
Ok, I reinstalled RStudio again and now it is working...

**Comment by matthewstrasiotto** [comment]
I've had a similar problem, but on commandline R, not clear why, and multiple `callr` sessions appeared to launch w/o fail prior to the one that brought down my run. 

I'm running a `drake` workflow on a HPC system, so there's a bit going on

**Comment by gaborcsardi** [comment]
@matthewstrasiotto Try to print the error object, it has the stdout and stderr of the failed R process. On Unix this includes a C stack trace. E.g. if I make my `.Rprofile` fail with `callr:::crash()`, I can see this:

```
> callr::r(function() Sys.getpid(), user_profile = TRUE)
Error in get_result(output = out, options) :
  callr subprocess failed: could not start R, exited with non-zero status, has crashed or was killed
Type .Last.error.trace to see where the error occured
> .Last.error.trace

 Stack trace:

 1. callr::r(function() Sys.getpid(), user_profile = TRUE)
 2. callr:::get_result(output = out, options)
 3. throw(new_callr_error(output, killmsg))

 x callr subprocess failed: could not start R, exited with non-zero status, has crashed or was killed

> cat(.Last.error$stderr)

 *** caught segfault ***
address 0x50, cause 'memory not mapped'

Traceback:
 1: get("attach")(structure(list(), class = "UserDefinedDatabase"))
 2: callr:::crash()
 3: eval(ei, envir)
 4: eval(ei, envir)
 5: withVisible(eval(ei, envir))
 6: source(".Rprofile", local = TRUE)
An irrecoverable exception occurred. R is aborting now ...
```

I am not sure how you can get this out from drake, but maybe there is a way.

**Comment by vjcitn** [comment]
Running into something similar ... callr invoked by pkgdown triggered the problem, but it can be triggered with callr::r(date).
Happens with both the cran and current github versions of callr.

```
R version 4.0.3 (2020-10-10) -- "Bunny-Wunnies Freak Out"
Copyright (C) 2020 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> callr::r(date)
Error in get_result(output = out, options) : 
  callr subprocess failed: could not start R, exited with non-zero status, has crashed or was killed
Type .Last.error.trace to see where the error occured
> .Last.error.trace

 Stack trace:

 1. callr::r(date)
 2. callr:::get_result(output = out, options)
 3. throw(new_callr_error(output, killmsg))

 x callr subprocess failed: could not start R, exited with non-zero status, has crashed or was killed 

> .Last.error$stderr
[1] "Error in dyn.load(tmpsofile) : \n  unable to load shared object '/tmp/RtmpIxCqrm/file64237561160.so':\n  /tmp/RtmpIxCqrm/file64237561160.so: failed to map segment from shared object: Operation not permitted\nCalls: <Anonymous> -> dyn.load\nExecution halted\n"
> sessionInfo()
R version 4.0.3 (2020-10-10)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: CentOS Linux 7 (Core)

Matrix products: default
BLAS:   /app/R-4.0.3@i86-rhel7.0/lib64/R/lib/libRblas.so
LAPACK: /app/R-4.0.3@i86-rhel7.0/lib64/R/lib/libRlapack.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] processx_3.5.0   compiler_4.0.3   R6_2.5.0         callr_3.5.1.9000
[5] ps_1.6.0        
> 
```

**Comment by gaborcsardi** [comment]
@vjcitn It seems that your config does not allow loading a shared lib from tmp. I'll open a separate issue for this.

**Comment by jennysjaarda** [comment]
@matthewstrasiotto did you ever find a solution to this issue with your `drake` pipeline? I am having the same problem, but with `targets`, I suspect it's the same underlying issue...

**Comment by llrs** [comment]
I am facing the same problem as @jennysjaarda:

```
Error: callr subprocess failed: could not start R, exited with non-zero status, has crashed or was killed
Visit https://books.ropensci.org/targets/debugging.html for debugging advice.
Backtrace:
    █
 1. └─targets::tar_make()
 2.   └─targets:::callr_outer(...)
 3.     └─base::tryCatch(...)
 4.       └─base:::tryCatchList(expr, classes, parentenv, handlers)
 5.         └─base:::tryCatchOne(expr, names, parentenv, handlers[[1L]])
 6.           └─value[[3L]](cond)
 7.             └─targets::tar_throw_run(...)
Execution halted
```

I found a possible workaround on https://github.com/ropensci/targets/issues/505, use `tar_make(callr_function = NULL)` which should be safe if run from a fresh R session. So it seems that it is an issue on targets. Hope this helps anyone who might find this on the future.

**Comment by jennysjaarda** [comment]
I solved this problem by allocating more memory to my job. Hope it helps!

**Comment by llrs** [comment]
Thanks, it might be related and I was already monitoring it (and might be the underlying cause of my problems).

**Comment by JohnGavin** [comment]
Thanks everyone, 
Fyi, callr_function = NULL, resolved a similar issue inside an isolated Nix env on a mac M2 (in an Rstudio terminal)
tar_make(
  # inside Nix --pure on max M2 via rix::rix_init()
  callr_function = NULL, ...
)

**Comment by bomeara** [comment]
I just had this issue with `targets` as well (also for a high memory job, MacBook Pro M4), and `tar_make(callr_function = NULL)` seems to have fixed it for me. So, thanks @llrs.
