### ISSUE TITLE
callr with crashing R process

### ISSUE THREAD

**Issue by llrs** [r-lib/callr#143]
I am not sure it is worth mentioning but in case someone has similar troubles I report this here.

I have some trouble generating the reprex of a process that ends up killing the R process. It makes Rstudio crash and hang up the bare R session (with core dumps).

```r
reprex::reprex({
+     # install.packages("BiocManager")
+     # BiocManager::install(c("affy", "affydata"))
+     library("affy")
+     library("affydata")
+     data(Dilution)
+     Dilution
+     eset <- rma(Dilution)
+     
+     Dilution0 <- Dilution[-c(1:4), ]
+     eset <- rma(Dilution0)})
```
The error I see is 

```
Rendering reprex...
 
Error: <callr_status_error in get_result(output = out, options):
 callr subprocess failed: could not start R, exited with non-zero status, has crashed or was killed>

See `.Last.error.trace` for a stack trace.
```
.Last.error.trace:
```
 Stack trace:

 1. reprex::reprex({ ...
 2. reprex:::reprex_render(r_file, std_file)
 3. callr::r_safe(function(input) { ...
 4. callr:::get_result(output = out, options)
 5. throw(new_callr_error(output, killmsg))

 x callr subprocess failed: could not start R, exited with non-zero status, has crashed or was killed 

Warning message:
partial match of 'topenv' to 'topenvs' 
```
I don't know if this could be handled different on the reprex side or on the callr side. 
I expected to get at least the same message that I see on the R session without RStudio

**Comment by gaborcsardi** [comment]
Hi, this is a reprex issue I think. callr correctly tells you that the process has exited with a non-zero status, and there is not much more it can do.

reprex could handle this, and I think it probably should, as people want to create reprexes that crash. 

Here is a minimal reprex btw:

```r
❯ reprex::reprex({ callr:::crash() })
Rendering reprex...
Error in get_result(output = out, options) :
  callr subprocess failed: could not start R, exited with non-zero status, has crashed or was killed
```

As a workaround for now, you can run the code that crashes in another callr R session. E.g. for a reprex like this, 

```r
out <- tempfile()
callr::r(
  function() { cat("running\n"); callr:::crash() },
  stdout = out, stderr = "2>&1"
)
cat(readLines(out), sep = "\n")
```

you get this output from reprex:

``` r
out <- tempfile()
callr::r(
  function() { cat("running\n"); callr:::crash() },
  stdout = out, stderr = "2>&1"
  )
#> Error in get_result(output = out, options): callr subprocess failed: could not start R, exited with non-zero status, has crashed or was killed
cat(readLines(out), sep = "\n")
#> running
#> 
#>  *** caught segfault ***
#> address 0x50, cause 'memory not mapped'
#> 
#> Traceback:
#>  1: get("attach")(structure(list(), class = "UserDefinedDatabase"))
#>  2: callr:::crash()
#>  3: (function () {    cat("running\n")    callr:::crash()})()
#> An irrecoverable exception occurred. R is aborting now ...
```

<sup>Created on 2020-02-06 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

(I cut out the bottom part of the stack, that belong to the callr magic and it is not relevant here.)

**Comment by llrs** [comment]
Oh, this is quicker. Thanks I'll raise there the issue.

**Comment by DavisVaughan** [comment]
@gaborcsardi 

I think im having this issue as well, but its hard to reproduce. If I open the `tidyverse.org` R project, then I get this:

```r
> callr::r(function() ls())

Error: <callr_status_error in get_result(output = out, options):
 callr subprocess failed: could not start R, exited with non-zero status, has crashed or was killed>

See `.Last.error.trace` for a stack trace.
```

If I open the vctrs R project, it works.

**Comment by DavisVaughan** [comment]
Oooh if I clear out the `.Rprofile` in the tidyverse.org repo then it works

**Comment by gaborcsardi** [comment]
@DavisVaughan that does not seem like the same issue to me, `ls()` probably does not crash. 

You probably have something the local profile that fails. callr now loads `.Rprofile` by default, to please packrat and renv, but you can opt out via `user_profile = FALSE`.
