### ISSUE TITLE
Documentation: how to use r or r_bg in a package to call other package functions

### ISSUE THREAD

**Issue by daattali** [r-lib/callr#147]
Suppose I'm developing a package `mypkg` that has a function `myfxn()` that makes a call to another internal (ie not exported) function:

```
#' @export
myfxn <- function() {
  some_slow_fxn()
}
```

Because this is slow, I want to run it in a background process asynchly. So I naively tried

```
#' @export
myfxn <- function() {
  callr::r_bg(function() some_slow_fxn())
}
```

But this doesn't work because `could not find function "some_slow_fxn"`

I could use `myfxn:::some_slow_fxn` instead, but then CRAN would cry, and so would I.

I could probably pass in the function itself as an argument, but that seems terrible. There must be a proper solution that I'm somehow overlooking, but I couldn't find any info in the documentation about how to use in a package.

**Comment by gaborcsardi** [comment]
```r
#' @export
myfxn <- function() {
  callr::r_bg(function() asNamespace("mypkg")$some_slow_fxn())
}
```

**Comment by daattali** [comment]
I fully support the decision to have a clean environment. My usecase here is definitely less common. If you think it's common *enough* then I can change this issue from a "documentation request" to a feature request, otherwise you can close this

**Comment by gaborcsardi** [comment]
Yeah, we can keep it open, I'll have a new release in a week or so, and then look at this again. Documenting it is not great, because it is essentially a receipt to go around an `R CMD check` warning. Even though I think in this case it should be considered a false positive.

But maybe I can support it somehow, via an extra argument to `r()` and `r_bg()`, etc. It is actually a use case that comes of often in my packages.

**Comment by daattali** [comment]
If it could be supported by a parameter to `r`/`r_bg` that would be a nice addition. Changed the issue title.

**Comment by gaborcsardi** [comment]
Probably the best is to document this, I decided. :)

**Comment by daattali** [comment]
Sounds good. I've run out of tears, I won't cry over this solution anymore :)
