### ISSUE TITLE
Feature request: Wait until R subprocess completes initializing before returning

### ISSUE THREAD

**Issue by daattali** [r-lib/callr#149]
Related to [this comments](https://github.com/r-lib/callr/issues/148#issuecomment-602115164)

> The `Sys.sleep(1)` is needed, because if we interrupt immediately, then the R subprocess has not even started yet. There is not much we can do in this case, obviously the finalizers will not run if R is interrupted while starting up.

That feels a bit hacky to me. It would be nice to have a way to tell `r_bg()` to not return until the subprocess started instead of having to add a manual sleep for an arbitrary time.

**Comment by gaborcsardi** [comment]
You don't have to wait in general. It was only included there for the test case. Usually you don't want to wait for the R process, the point is that `r_bg()` returns as soon as possible.

**Comment by daattali** [comment]
I'm actually running into a case where I **need** to add this sleep in a real scenario, not just in theory.

I can expand on my usecase if you're interested/if it matters.

**Comment by gaborcsardi** [comment]
`r_bg()` is a one-shot background process. If you need to synchronize the two processes, then maybe the `r_session` class is better for you?

**Comment by daattali** [comment]
You're right that having to rely on waiting for the process to begin makes it sound like r_session would be more fitting.

The only situation I see this being potentially an issue is with a finalizer. If #148 ends up getting implemented, then I'd want to be sure that the child process gets initialized so that I can be sure that its finalizer is called. It would be unexpected behaviour to spawn a child process with a finalizer and never have that finalizer called because the process never started on time. 

I'll close this issue because it's more of a discussion point for #148

**Comment by gaborcsardi** [comment]
> then I'd want to be sure that the child process gets initialized so that I can be sure that its finalizer is called.

This is duplicating a feature of `r_session`, so I guess you can just use that? You can start up a session with `wait = TRUE`, and then `$run()` to install the finalizer.
