### ISSUE TITLE
run process in a docker container?

### ISSUE THREAD

**Issue by vnijs** [r-lib/callr#153]
Lets say I'm running R(studio) on macOS. Could callr send code and receive ouput from a docker container running on the same machine?

**Comment by gaborcsardi** [comment]
That would be a really cool feature, but I am afraid that callr/processx are not great for this. They need the same disk for example, to pass data between the processes.

**Comment by vnijs** [comment]
Thanks for the reply @gaborcsardi. You could mount a directory when the docker container starts ("-v ~:/home/rstudio"). Would that not be sufficient?

**Comment by gaborcsardi** [comment]
That's a step, yes, but the are also Unix sockets between the main process and the subprocess, and he main process also sends signals and interrupts sometimes. Solving all this for Docker, in a portable way, is probably too much to fit in callr.

**Comment by vnijs** [comment]
Understood. Thanks for your consideration @gaborcsardi
