### ISSUE TITLE
Problems importing python modules with reticulate using r_bg()

### ISSUE THREAD

**Issue by iwillham** [r-lib/callr#155]
Hi there,
I'm trying to run some cluster analysis using the [leiden](https://github.com/TomKellyGenetics/leiden) package in a background process with `callr::r_bg()`. This package implements the Python version of the leiden algorithm using `reticulate`. When running:

 `rx = r_bg(function(g) {leiden::leiden(g)}, args = list(g=g))` 

I get the following error from `.Last.error.trace`

```
Stack trace:
1. rx$get_result()
2. callr:::rp_get_result(self, private)
3. callr:::get_result(out, private$options)
4. throw(new_callr_error(output, killmsg))

x callr subprocess failed: could not start R, exited with non-zero status, has crashed or was killed
```

I also get this same error message when trying to import python modules in the background process i.e., `rx = r_bg(function() {reticulate::import("numpy")})`. I am able to run these functions in the main thread and I am able to run other reticulate functions like `reticulate::py_discover_config()` with `r_bg()`. Any ideas of what might be causing this error or potential workarounds?

Additional info: Using R4.0.0 on RStudio 1.2.5042 with callr_3.4.3, reticulate_1.15, and processx_3.4.2. I also have set my user .Rprofile to get Rstudio to use Python 3 as the default. I'm guessing this is causing issues but I tried playing around with `system_profile` and `user_profile` to no avail.

**Comment by gaborcsardi** [comment]
You'll have to find out why the process cannot start. Look at `.Last.error`, and what's in it: `names(.Last.error)`. You should be able to get the standard output and/or error from there, hopefully with a better error report.

**Comment by iwillham** [comment]
I checked `.Last.error$stderr` and `.Last.error$stdout` and unfortunately they are both empty...

**Comment by gaborcsardi** [comment]
Can you try to create a reproducible example?

**Comment by iwillham** [comment]
I'm still new at this but I hope this is what you are asking for. Let me know if there is something I can add to make it more reproducible.

```
library(callr); library(reticulate)
rx = r_bg(function() {reticulate::import("numpy")})
rx$get_result()
```

```
sessionInfo()
R version 4.0.0 (2020-04-24)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Catalina 10.15.4

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] reticulate_1.15 callr_3.4.3    

loaded via a namespace (and not attached):
 [1] processx_3.4.2  compiler_4.0.0  Matrix_1.2-18   R6_2.4.1        tools_4.0.0     Rcpp_1.0.4.6   
 [7] grid_4.0.0      jsonlite_1.6.1  ps_1.3.2        lattice_0.20-41
```

**Comment by gaborcsardi** [comment]
What I need is some self-contained code that I can run to get the same error as you. If I run this:

```r
library(callr); library(reticulate)
rx = r_bg(function() {reticulate::import("numpy")})
rx$get_result()
```

then I get
```
Error in rp_get_result(self, private) : Still alive
Type .Last.error.trace to see where the error occured
```

Is this the error you get?

**Comment by iwillham** [comment]
This is actually not the error I get. I neglected to mention that I wait maybe ~10 seconds after calling `r_bg()` at which point `rx$is_alive()` is inevitably `FALSE`. So the code below is more representative of what I'm doing:

```
library(callr); library(reticulate)
rx = r_bg(function() {reticulate::import("numpy")})
rx$wait()
rx$get_result()
```

Thanks for the help!

**Comment by gaborcsardi** [comment]
This does not error for me:
```
> library(callr); library(reticulate)
> rx = r_bg(function() {reticulate::import("numpy")})
> rx$wait()
> rx$get_result()
<pointer: 0x0>
```

**Comment by iwillham** [comment]
Bizarre, I'll try playing around with it some more. Thanks for looking into it.
