### ISSUE TITLE
[support request]  create r_session without using the current R profile

### ISSUE THREAD

**Issue by julou** [r-lib/callr#156]
hi, I'm trying to create a new background r_session without using the current R profile, but somehow the session appears as "finished" as soon as it is created…

```
> callr::r_session_options(cmdargs=c(callr::r_session_options()$cmdargs, '--no-init-file')) %>% callr::r_session$new() 

R SESSION, finished, pid 30072.
```

Is is the expected behaviour? am I doing something wrong?

I'm trying this because `multidplyr` relies on r_session and when I try to create a cluster of e.g. 30 workers in a project with `renv`, it takes 5-6 sec per worker to initialise (so 3 min in total!). Let me know if you think I'm completely off and that creating sessions without initialising renv is bound to fail…

Thank you very much.

**Comment by gaborcsardi** [comment]
This is the way to ignore the user and local R profile:
```r
rs <- callr::r_session$new(
  callr::r_session_options(user_profile = FALSE)
)
```
Whether this will work with renv, I don't know. My guess would be that it will not, except if you set up the library path manually, or install the same packages into a user library or the system library.

**Comment by julou** [comment]
thanks, it might very well fix my issue :)
