### ISSUE TITLE
mclapply makes callr "Error while shutting down parallel"

### ISSUE THREAD

**Issue by mschubert** [r-lib/callr#158]
If I run the following code in an R script, it works as expected:

```r
p = callr::r_bg(function() Sys.sleep(30))
p$kill_tree()
```

However, if I add this to a `testthat` test I get a long delay and shutdown error:

```r
test_that("mwe callr", {
    p = callr::r_bg(function() Sys.sleep(30))
    p$kill_tree()
})
# long delay after finishing all tests
# Error while shutting down parallel: unable to terminate some child processes
```

I'm not sure if this is a `callr`, `processx` or `testthat` bug, but I would think the behavior is not intended.

`sessionInfo()`:
```r
R version 4.0.2 (2020-06-22)
Platform: x86_64-pc-linux-gnu (64-bit)

other attached packages:
[1] testthat_2.3.2 callr_3.4.3

loaded via a namespace (and not attached):
 [1] processx_3.4.2   compiler_4.0.2   magrittr_1.5     R6_2.4.1
 [5] assertthat_0.2.1 cli_2.0.2        tools_4.0.2      glue_1.4.1
 [9] crayon_1.3.4     fansi_0.4.1      ps_1.3.3         rlang_0.4.6
[13] rdoc_0.1.0
```

**Comment by gaborcsardi** [comment]
Thanks! I can't reproduce this, unfortunately. Can you please try to create a reprex with the reprex package? Thanks.

**Comment by mschubert** [comment]
My apologies, I should have checked that the above lines actually reproduce the error when run in isolation (i.e., not in my package).

And I was wrong, the actual error is caused and reproducible by:

```r
x = parallel::mclapply(1:5, function(x) x*2)
y = callr::r(function() Sys.sleep(1))
z = parallel::mclapply(1:5, function(x) x*2)
# Error while shutting down parallel: unable to terminate some child processes
```

Both the `mclapply` calls _before and after_ are required to reproduce this.

**Comment by gaborcsardi** [comment]
This does not generate any error for me, still.

**Comment by mschubert** [comment]
Have you put it in a script and run this?

**Comment by gaborcsardi** [comment]
So, this is a completely different issue than the one you originally reported?

Yes, this is a known issue, and the only solution is to avoid using mclapply and processx together. You have already linked the relevant issues, this is a duplicate.

**Comment by mschubert** [comment]
You're right, I misunderstood the closed issue for a fix, not a workaround that still needs to be explicitly set.
