### ISSUE TITLE
Calls disappearing into thin air?

### ISSUE THREAD

**Issue by condour** [r-lib/callr#161]
If I run this reprex, I get only some random number of the happy{x}.txt files to say "done with wait".. the others will randomly not write anything. It will do this randomly even with very small iterations, like 1:10, although the chances of success are greater.

Am I missing a key limitation or OS setting?

This is on RStudio Server (running in docker) Version 1.2.5042 and R v 3.6.3

```
library(callr)

doAWait <- function() {
  Sys.sleep(3)
  print("done with wait")
}

for(i in 1:50) {
  callr::r_bg(doAWait, stdout=paste0("answers/happy", i, ".txt"))
}

```

**Comment by gaborcsardi** [comment]
You do not store the objects returned by `callr::r_bg` anywhere, so the R GC will collect them, which means that the processes will be killed, before they can write something, potentially. So, yeah, PEBKAC.

**Comment by gaborcsardi** [comment]
You do not store the objects returned by `callr::r_bg` anywhere, so the R GC will collect them, which means that the processes will be killed, before they can write something, potentially.

**Comment by condour** [comment]
Thanks!!!
