### ISSUE TITLE
Attach existent R session as a subprocess to another R session

### ISSUE THREAD

**Issue by 229668880** [r-lib/callr#169]
After starting two independent R sessions, can one of them be attached to the other as a subsession? just like one session created by r_session$new().

I am thinking about how to make communication between two R sessions using callr package.

**Comment by gaborcsardi** [comment]
That would be cool indeed, but not possible currently. In theory you could use a FIFO/pipe to communicate, with the `fifo()` function, but in my experience it does not work well on Windows.

You can also look at the `rzmq` package, this uses zeromq.

**Comment by 229668880** [comment]
Thanks for your reply. Let me try.
