### ISSUE TITLE
Error: callr subprocess failed: no se pudo encontrar la función "%>%"

### ISSUE THREAD

**Issue by ogorodriguez** [r-lib/callr#170]
Hi, I am trying to run workflowr (ver 1.6.2) and I am getting the error

Error: callr subprocess failed: no se pudo encontrar la función "%>%" 

when running wflow_build()

callr version used: 3.5.0

tidyverse and dplyr are called in library

**Comment by gaborcsardi** [comment]
I guess magrittr is not loaded in the child process. I don't know if this is a workflowr issue or not.

**Comment by ogorodriguez** [comment]
Hello @gaborcsardi thanks for this info.  I am following up now with workflowr in https://github.com/jdblischak/workflowr/issues/224.

**Comment by jdblischak** [comment]
Quick update: we figured out the issue. He was loading dplyr and tidyverse interactively in the R console but not in the Rmd file, so the code worked when run interactively, but not when run in the separate R session created by callr. In other words, workflowr worked as expected by failing to build the file.

@gaborcsardi Thanks for your quick diagnosis and sending @ogorodriguez my way.
