### ISSUE TITLE
make background session stderr and stdout synchronously

### ISSUE THREAD

**Issue by lz100** [r-lib/callr#173]
I am trying to get the stderr and stdout from a background session while some code is running, but it seems I can not redirect them to a file. Is there a way I can do it like `r(function(){xxx}, stdout = "log.txt", stderr = "log.txt")`?

Things I have tried:

1. open a session with options:
```r
rs <- callr::r_session$new(
    options = callr::r_session_options(
        stdout = "log.txt", 
        stderr = "log.txt")
)
```
However, the `rs$get_error_file()` is still `|` not the file name I want.

2. use `rs$read_error_lines()` to get stderr from the connection
```r
rs <- callr::r_session$new(
    options = callr::r_session_options(
        stdout = "log.txt", 
        stderr = "log.txt")
)
rs$call(function() {warning("stderr", call. = FALSE); Sys.sleep(5)})
time <- 0
while(rs$poll_process(1) != "ready"){
    cat(time, "s\n")
    print(rs$read_error_lines())
    time <- time + 1
    Sys.sleep(1)
}
rs$read_error_lines()
rs$read()
rs$close(grace = 1000)
``` 

```r
# 0 s
# character(0)
# 1 s
# character(0)
# 2 s
# character(0)
# 3 s
# character(0)
# 4 s
# character(0)
# 5 s
# character(0)
# > rs$read_error_lines()
# [1] "Warning message:" "stderr "         
# > rs$read()
# $code
# [1] 200
# 
# $message
# [1] "done callr-rs-result-22bd6c2ce88"
# 
# $result
# NULL
# 
# $stdout
# NULL
# 
# $stderr
# NULL
# 
# $error
# NULL
# 
# attr(,"class")
# [1] "callr_session_result"
# > rs$close(grace = 1000)
# NULL
```
The error file is only updated after everything is done.

Is there a way I can keep it in the background and get stderr and stdout synchronously?

**Comment by gaborcsardi** [comment]
I don't think this is possible currently. It would not be too hard to add it, though.

**Comment by lz100** [comment]
Great. That will be very helpful if we want to do something in the parent session as soon as we capture certain outputs in the child session.

**Comment by gaborcsardi** [comment]
> Great. That will be very helpful if we want to do something in the parent session as soon as we capture certain outputs in the child session.

This actually works, but don't redirect to files. Use pipes instead. Also, `warning()` printed is delayed, so that's not a good test:

```r
rs <- callr::r_session$new(
    options = callr::r_session_options(
        stdout = "|", 
        stderr = "|")
)
rs$call(function() { cat("stderr\n", file = stderr()); Sys.sleep(2)})

processx::poll(list(rs$get_error_connection()), -1)
rs$read_error()

rs$poll_process(-1)
rs$read()
rs$close(grace = 1000)
```

The `processx::poll()` call waits until there is output in stderr. You can use it with a positive timeout (in ms) or zero to not wait, just take a peek. This is better than a log file for getting notifications, because you can poll multiple processes, and will be notified as soon as there is output on one.

The caveats are:
1. If you don't read out the pipe, and the pipe buffer gets full, then the sub-process stops. This is actually a feature, as it gives you back-pressure.
2. The `rs$read()` call will not contain the stdout/stderr. But it will still be in the pipe, unless you read it out already.

Is this good? Or you really want a log file?

**Comment by lz100** [comment]
Thanks for the suggestions! I think still need a log file. I use it in my Shiny app. I run some code in the background and display the stdout and stderr on the UI. Meanwhile, I do some other things in the main app. After the session ends, users can download the log file. So I need to generate a log file sooner or later. 

My current solution is to `sink` everything on the child at start and run an observer in the parent every 1 second to watch for newly added lines in the log file and render it to UI, so it will not block the main session .
```r
rs$call(function(log_path) {
    log_file <- file(log_path, "awt")
    sink(log_file, append = TRUE, type = "o")
    sink(log_file, append = TRUE, type = "m")
    }, 
    args = list(log_path = normalizePath(log_path)
))
```
