### ISSUE TITLE
Symbolic arguments should be protected from evaluation

### ISSUE THREAD

**Issue by lionel-** [r-lib/callr#175]
```r
callr::r(identity, list(x = quote(foobar)))
#> Error: callr subprocess failed: object 'foobar' not found
#> Type .Last.error.trace to see where the error occured
```

Calls and symbols should be protected, for example with `base::enquote()`.

**Comment by gaborcsardi** [comment]
callr calls `do.call()` on the passed function and the arguments. So I guess it just needs `quote = TRUE`?

**Comment by lionel-** [comment]
Yup that will fix it.
