### ISSUE TITLE
Cannot open browser from callr process

### ISSUE THREAD

**Issue by wlandau** [r-lib/callr#177]
`callr::r(function() browseURL("https://github.com"))` does not open a browser window even though `browseURL("https://github.com")` does. This is relevant for non-blocking Shiny apps, e.g. `shiny::runApp(launch.browser = TRUE)`.

**Comment by wlandau** [comment]
Motivation: https://github.com/wlandau/targets/pull/248. My workaround is to launch the app in `r_bg()` and then call `browseURL()` from the parent process, but it is not perfect because the browser usually launches before the app can initialize. I am not sure how `shiny::runApp()` avoids this problem.

**Comment by gaborcsardi** [comment]
That is intentional: https://github.com/r-lib/callr/blob/5cf65b9fa188dc641d3a6949389827c3f19a68b4/R/rcmd.R#L106

For the early use cases we did not want subprocesses to open browsers. It is somewhat different nowadays, but probably too late to change.

Workaround:
```r
callr::r(
  function() browseURL("https://github.com"), 
  env = c(R_BROWSER = Sys.getenv("R_BROWSER"))
)
```

**Comment by wlandau** [comment]
Thanks, @gaborcsardi. That's totally fair. 

I actually figured out a different workaround that does not require `R_BROWER`: 

* Child: pass the host and port to `options` in `shinyApp()`.
* Parent: ping the port until it is up, then call `browseURL()`.

Currently using this in `targets::tar_watch()` and `proffer::serve_pprof()`.
