### ISSUE TITLE
How to save the data once process is finished in shiny?

### ISSUE THREAD

**Issue by fmmattioni** [r-lib/callr#179]
I was wondering what would be the correct way of retrieving the data once the process has finished, and then use these data in a plot, for example? Ideally, I would like to save the results in a `reactiveValues()` or `reactive()`. Is this possible?

reprex:

```r
library(shiny)
library(callr)
library(ggplot2)

ui <- fluidPage(
  plotOutput("plot")
)

server <- function(input, output, session) {
  
  slow_function <- callr::r_bg(
    func = function() {
      Sys.sleep(2)
      mtcars
    },
    supervise = TRUE
  )
  
  output$plot <- renderPlot({
    req(!slow_function$is_alive())
    
    ggplot(slow_function$get_result(), aes(mpg, hp)) +
      geom_point()
  })
}

shinyApp(ui, server)
```

Thanks in advance!

**Comment by gaborcsardi** [comment]
You would need to wait for the process to finish, e.g. via `slow_function$poll()`. 

I am not entirely sure about the best wait to combine this with the shiny event loop and reactives, etc.

**Comment by fmmattioni** [comment]
Thank you very much for the reply, @gaborcsardi !

What I have been doing is the following:

```r
  r <- reactiveValues(df = NULL)
  
  autoInvalidate <- reactiveTimer(1000)
  
  observe({
    if(slow_function$is_alive()) {
      autoInvalidate()
    } else {
      r$df <- slow_function$get_result() 
    }
  })
```

I am not sure this is the best way to do it, but it has been working quite nicely.

**Comment by gaborcsardi** [comment]
Indeed it is not the best way, because the process might be alive, but still writing out the result, and then `get_result()` might fail. Might happen for bigger results or slower machines, etc.

A better way is to it is to call `poll_io()`, that will return `"ready"` when the result is available:

```r
slow_function <- callr::r_bg(
  func = function() {
    Sys.sleep(2)
    mtcars
  },
  supervise = TRUE
)

slow_function$poll_io(0)["process"]
#>   process
#> "timeout"

# A bit later
slow_function$poll_io(0)["process"]
#> process
#> "ready"
```

You also don't really need `supervise = TRUE` I think.

**Comment by fmmattioni** [comment]
Oh, got it! Thank you!!!

**Comment by D3SL** [comment]
In case you hadn't seen them you may also be interested in the `invalidateLater()` and `reactivePoll()` functions in base Shiny. The former is just a [safer/simpler non-blocking way](http://www.open-meta.org/technology/how-shinys-invalidatelater-actually-works/) for you to do exactly what you're already doing with `autoInvalidate()`, and [the latter](https://shiny.rstudio.com/reference/shiny/0.14/reactivePoll.html) takes the concept a step further.  Every X milliseconds `reactivePoll()` runs a "check function" and compares the current result for equality with past results, if there's been a change in output the second "value function" will be run.

**Comment by fmmattioni** [comment]
@D3SL this is great! Thanks a lot for the info! I am going to give these a try!
