### ISSUE TITLE
How to specify R path

### ISSUE THREAD

**Issue by liutiming** [r-lib/callr#181]
There are multiple versions of R installed on my cluster and when I used callr with https://github.com/ropensci/targets and https://github.com/mschubert/clustermq/, although I used R in 3.6.1 and r(function() Sys.which("R")) also returns 3.6.1, the job was submitted in R 4.0... is there an option to specify the path for callr?

**Comment by gaborcsardi** [comment]
callr alawys runs the same version of R in the subprocess, it uses `R.home()` to query the path of the current version: https://github.com/r-lib/callr/blob/65e336f7fd6806725759b1d28035113c592c2462/R/setup.R#L222

So if you can reproduce this, and you think it is a callr bug, then please send use some reproducible example.
