### ISSUE TITLE
Error collecting the result of a persistent background process if the parent exits early

### ISSUE THREAD

**Issue by wlandau** [r-lib/callr#183]
I have a specialized use case that requires a persistent background process.

```r
callr::r_bg(
  function() Sys.sleep(10),
  supervise = FALSE,
  cleanup = FALSE,
  stderr = "log.txt"
)
```

When I terminate the parent before the child finishes, the final error log looks like this.

```r
Error in gzfile(file, mode) : cannot open the connection
In addition: Warning messages:
1: In gzfile(file, mode) :
  cannot open compressed file '/var/folders/k3/q1f45fsn4_13jbn0742d4zj40000gn/T//Rtmp45hz6V/callr-res-84902bec782', probable reason 'No such file or directory'
2: In gzfile(file, mode) :
  cannot open compressed file '/var/folders/k3/q1f45fsn4_13jbn0742d4zj40000gn/T//Rtmp45hz6V/callr-res-84902bec782.error', probable reason 'No such file or directory'
```

I first thought it could be related to #148, but I got a similar result when I set `TMPDIR` to `"/Users/CENSORED/Desktop/" in a local `.Renviron`.

```r
Error in gzfile(file, mode) : cannot open the connection
In addition: Warning messages:
1: In gzfile(file, mode) :
  cannot open compressed file '/Users/CENSORED/Desktop/RtmpnqrWnn/callr-res-85b27c642752', probable reason 'No such file or directory'
2: In gzfile(file, mode) :
  cannot open compressed file '/Users/CENSORED/Desktop/RtmpnqrWnn/callr-res-85b27c642752.error', probable reason 'No such file or directory'
```

Session:

```r
> sessionInfo()
R version 4.0.3 (2020-10-10)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Catalina 10.15.7

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods  
[7] base     

other attached packages:
[1] callr_3.5.1

loaded via a namespace (and not attached):
[1] processx_3.4.5 compiler_4.0.3 tools_4.0.3    yaml_2.2.1    
[5] ps_1.5.0  
```

I got the same results using https://github.com/r-lib/callr/commit/0ca92e1df7db7fefd79f43dc7a687a499d92fe81.

**Comment by gaborcsardi** [comment]
The sub-process writes the result in the session temp dir of the main process. If you quit from the main process, it will delete its session temp dir, so the sub-process cannot write out its result.

I am not sure what you are trying to do here, but you are maybe not interested in the result of the sub-process, so you can maybe just terminate it before it is trying to write out the result:

```r
callr::r_bg(
  function() { Sys.sleep(1); tools::pskill(Sys.getpid()) },
  supervise = FALSE,
  cleanup = FALSE,
  stderr = "log.txt"
)
```

FWIW, I think it is better to make the main process live longer than the sub-process. 

`cleanup = FALSE` is also not great, and it is better to avoid it, as it can easily lead to rouge background processes that you cannot easily stop.

**Comment by wlandau** [comment]
I built a Shiny app that runs a [`targets`](https://github.com/ropensci/targets/issues) pipeline in the background. The underlying statistical workflow takes a long time to finish, so the server deliberately saves the PID and keeps the pipeline running after the user logs out. On the next login, the app recovers the PID and settings of the last project. The app runs on RStudio Connect with persistent user-specific storage.

So yes, I am not interested in the return value of the `callr` process because the meaningful results go to storage. `pskill(Sys.getpid())` would work, but only if I call it from [`tar_make()`](https://docs.ropensci.org/targets/reference/tar_make.html) when `callr_function` is `r_bg()`, which introduces new interface challenges on my end.

**Comment by gaborcsardi** [comment]
The main goal of callr is to control the background process, and communicate with it, so this is not a use case we considered. 

If you just want to start an independent background process, that's a much simpler problem, I guess you can start an R script with `system(..., wait = FALSE)`?

**Comment by wlandau** [comment]
True, `system()` route is much more aligned with my use case. The only roadblock is that the app does some final checks to avoid race conditions before releasing control back to the user, mainly to verify that the PID from the `callr` handle agrees with the PID in the log file. Is there a way to get the PID of the `system()`/`system2()` call reliably without going through storage?

**Comment by gaborcsardi** [comment]
IDK if there is a way to get the pid, but you can use `processx::process`, if `system()` is not good enough.

I am unsure if we want to implement sub-processes that survive the main process in callr, for now I'll close this issue.
