### ISSUE TITLE
Run external file in background process

### ISSUE THREAD

**Issue by markwsac** [r-lib/callr#188]
Thanks for this great package. First of all I apologize for asking this generic question about callr here. I just wanted to be sure about the approach to use this.

I am just wondering if source( ) is the right (and efficient) way to call external R script within r_bg( )
`r_bg(function() source("getdata.R"), supervise = T)`

`getdata.R` has some commands to read data from CSV/Excel and then followed by some data manipulation and writing it in Excel.

**Comment by gaborcsardi** [comment]
Yes, that would be fine. There is also an `rscript_process`, which is simpler if you don't want to copy the result of the script back to the main session.
