### ISSUE TITLE
Support for custom user functions

### ISSUE THREAD

**Issue by mlascaleia** [r-lib/callr#191]
Hi,

I am sorry if this is a basic question, but I am wondering if callr is able to support custom user functions that are defined in the global environment? I understand that the use of "::" is essential for functions from other packages, but custom user functions exist outside of any package. Here is an example of what I would like to be able to do:

```
x <- 3
userFunction <- function(x){
  y <- (2 * x + 7)
  return(y)
}

z <- r_bg(function(a) userFunction(a), args = list(x))
```
This currently returns the error:
```
Error: <callr_status_error: callr subprocess failed: could not find function "userFunction">
-->
<callr_remote_error in userFunction(a):
 could not find function "userFunction">
 in process 20466 
See `.Last.error.trace` for a stack trace.
```
Where the code below works just fine
```
x <- 3
z <- r_bg(function(a) sum(a), args = list(x))
```

Thank you!

**Comment by gaborcsardi** [comment]
You can pass the functions as arguments:

``` r
library(callr)

x <- 3
userFunction <- function(x) {
  y <- (2 * x + 7)
  return(y)
}

xp <- list(x = x, userFunction = userFunction)

z <- r_bg(function(xp) {
  for (n in names(xp)) .GlobalEnv[[n]] <- xp[[n]]
  userFunction(x)
}, args = list(xp))

z$wait()
z$get_result()
#> [1] 13
```

<sup>Created on 2021-03-23 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by mlascaleia** [comment]
Thank you so much
