### ISSUE TITLE
R_PROFILE_USER cannot be set in `env` for `callr::r`

### ISSUE THREAD

**Issue by MilesMcBain** [r-lib/callr#193]
``` r
callr::r(
    function() {
    print(Sys.getenv("MY_ENV"))
    print(Sys.getenv("R_PROFILE_USER"))
    },
    user_profile = TRUE,
    env = c(
        "R_PROFILE_USER" = "~/.Rprofile",
        "MY_ENV" = "MILES"
    ),
    show = TRUE
)
#> [1] "MILES"
#> [1] ""
#> [1] ""
```

<sup>Created on 2021-03-31 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

I was expecting this to work, in combination with `user_profile = TRUE` so that I could set the profile for the session to a specific file.

**Comment by gaborcsardi** [comment]
`callr::r()` uses the profile to make sure the config of the child process matches the current process, so you can't point it to a different file. OTOH it tries to copy the current settings, so this works:

```r
tmp <- tempfile()
cat("foo <- 42\n", file = tmp)
Sys.setenv(R_PROFILE_USER = tmp)

callr::r(function() foo, user_profile = FALSE)
#> Error: callr subprocess failed: object 'foo' not found
#> Type .Last.error.trace to see where the error occurred

callr::r(function() foo, user_profile = TRUE)
#> [1] 42
```

**Comment by gaborcsardi** [comment]
@MilesMcBain Is this workaround OK for your use case?

**Comment by MilesMcBain** [comment]
I think the curent workaround is fine if documented.

It can make my example work with this and It doesn't work for my usecase but I think that is due to `{targets}`.

**Comment by gaborcsardi** [comment]
Actually, I think I fixed it, hopefully without breaking anything else...
