### ISSUE TITLE
r_vanilla() has profile = "user_profile" as default

### ISSUE THREAD

**Issue by krlmlr** [r-lib/callr#194]
This contradicts documentation. Should it be `r_vanilla(user_profile = FALSE)` by default?

**Comment by gaborcsardi** [comment]
Yes, I think so.

**Comment by gaborcsardi** [comment]
Actually, `"project"` is not too bad, either, because you probably still want to load renv and packrat profiles?

**Comment by krlmlr** [comment]
Not sure. Vanilla is vanilla, how much more vanilla can I ask for?

It was surprising and has cost time. It might be easier to document this than the other way round. I think most of the time users want `r()`, I have used `r_vanilla()` only once ... to call a session and ignore renv's profile :upside_down_face:
