### ISSUE TITLE
r_bg process hangs rather than completing

### ISSUE THREAD

**Issue by mpadge** [r-lib/callr#204]
Reproducible example (also checked in clean container, so independent of my OS, and unrelated to [previous `processx` stuff](https://github.com/r-lib/processx/issues/300)):
``` r
f <- tempfile (fileext = ".Rmd")
writeLines (letters, con = f)
out <- paste0 (tools::file_path_sans_ext (f), ".html")
ps <- callr::r (rmarkdown::render, args = list (input = f, output_file = out), package = TRUE)
# all okay; returns local path as expected
ps <- callr::r_bg (rmarkdown::render, args = list (input = f, output_file = out), package = TRUE)
```
That call hangs and does not return. It does do some stuff:
``` r
ps$get_status()
#> [1] "sleeping"
ps$read_output()
#> [1] "\r  |                                                                            \r  |                                                                      |   0%\r  |                                                                            \r  |......................................................................| 100%

  ordinary text without R code

/usr/bin/pandoc +RTS -K512m -RTS file91f9306b028c.knit.md --to html4 --from markdown+autolink_bare_uris+tex_math_single_backslash --output /tmp/RtmpABk5dv/file91f9306b028c.html --lua-filter /usr/lib/R/library/rmarkdown/rmarkdown/lua/pagebreak.lua --lua-filter /usr/lib/R/library/rmarkdown/rmarkdown/lua/latex-div.lua --self-contained --variable bs3=TRUE --standalone --section-divs --template /usr/lib/R/library/rmarkdown/rmd/h/default.html --no-highlight --variable highlightjs=1 --variable theme=bootstrap --include-in-header /tmp/RtmpRLi3vT/rmarkdown-str95755361c30f.html --mathjax --variable 'mathjax-url:https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML' \n"
> ps$read_error()
#> [1] "\n\nprocessing file: file91f9306b028c.Rmd\noutput file: file91f9306b028c.knit.md\n\n[WARNING] This document format requires a nonempty <title> element.\n"
```
The error is just the usual warning redirect; the 100% in the output shows the pandoc rendering worked, and:
``` r
any (grepl (basename (f), list.files (ps$get_wd())))
#> [1] TRUE
```
The call did its job; the function has a default return value; and yet .. `r_bg` just sleeps rather than returning. Any ideas?

**Comment by gaborcsardi** [comment]
I can't reproduce this on my system, so I am afraid you'll have to tell me more about your platform(s).

**Comment by gaborcsardi** [comment]
Are you sure that this is not just because you don't read out the stdout/stderr pipes? See https://github.com/r-lib/processx#standard-output-and-error:
> Always make sure that you read out the standard output and/or error of the pipes, otherwise the background process will stop running!

**Comment by mpadge** [comment]
Oh damnit, sorry to hear. My system you know about - archlinux, everything at it's latest. I can also reproduce on multiple docker containers, including `tidyverse:latest`. I'm checking on a few other containers, but all seems reproducible. Have you tried in docker? (And yes, it's not related to stdout/stderr pipes - i've tried redirecting those, to no effect.)

**Comment by mpadge** [comment]
Just span up `rocker/base-r` with minimal installs, and can reproduce there too

**Comment by mpadge** [comment]
But all works fine on remote `ssh` to Ubuntu 18.04. Strange - leave it with me for a while, and i'll see what else i can dig up. Thanks for responding :smile:

**Comment by gaborcsardi** [comment]
I can't reproduce it in containers. 

Again, make sure that you read out the stdout and stderr. I.e. you need to call `$read_output()` and `$read_error()` many times, in a loop, when managing a background process. Or redirect them to files.

**Comment by mpadge** [comment]
Yep, redirecting them to files did the trick. Thanks!
