### ISSUE TITLE
Error with callr when called from within targets::tar_make() in renv project

### ISSUE THREAD

**Issue by adamaltmejd** [r-lib/callr#207]
See here: https://github.com/ropensci/targets/discussions/506.

Basically callr throws one of these errors when I run targets::tar_make() and `RENV_CONFIG_USER_PROFILE` is set in .Renviron. Not sure if this is an `renv`, `callr` or `targets` issue.

```
Error in if (!enabled) return(FALSE) :
  missing value where TRUE/FALSE needed
Calls: source ... renv_bootstrap_load -> <Anonymous> -> renv_load_rprofile
Traceback (most recent calls last):
17: source(".Rprofile", local = TRUE)
16: withVisible(eval(ei, envir))
15: eval(ei, envir)
14: eval(ei, envir)
13: source("renv/activate.R")
12: withVisible(eval(ei, envir))
11: eval(ei, envir)
10: eval(ei, envir)
 9: local(...)
 8: eval.parent(substitute(eval(quote(expr), envir)))
 7: eval(expr, p)
 6: eval(expr, p)
 5: eval(quote(...), new.env())
 4: eval(quote(...), new.env())
 3: renv_bootstrap_load(project, libpath, version)
 2: renv::load(project)
 1: renv_load_rprofile(project)
Execution halted
Error: callr subprocess failed: could not start R, exited with non-zero status, has crashed or was killed
Visit https://books.ropensci.org/targets/debugging.html for debugging advice.
```

or, if TAR_MAKE_REPORTER="timestamp"

```
Error in dyn.unload(env$.path) :
  shared object '/tmp/RtmpAf1Tsp/callr-client--2e18fe9.so' was not loaded
Calls: <Anonymous> -> <Anonymous> -> dyn.unload
```

But the error only shows up when `RENV_CONFIG_USER_PROFILE` is set. It doesn't matter if its set to true or false though. Very strange.

**Comment by gaborcsardi** [comment]
> Basically callr throws one of these errors

I don't think this error is from callr, because

```
if (!enabled) return(FALSE) :
  missing value where TRUE/FALSE needed
```

this code is not in callr. It looks like renv code, e.g.
https://github.com/rstudio/renv/blob/de4c3cccce8ebc267e1c3c6a76dbdf001739d96a/R/load.R#L496 and other places:
https://github.com/rstudio/renv/search?q=if+enabled+return+false

**Comment by adamaltmejd** [comment]
Thanks! I'll post it in the renv repo too.

**Comment by adamaltmejd** [comment]
I'm not sure actually if this is only an renv error. At least the second part looks like it could be on the callr side. Please run the shell script in this repo to reproduce: https://github.com/adamaltmejd/renv_callr_targets_error
