### ISSUE TITLE
Add to documentation that `extra` in `rscript_process_options` is for passing options to `processx::process`

### ISSUE THREAD

**Issue by burgerga** [r-lib/callr#208]
I am starting a long running script from shiny so I wanted `cleanup = F`, but it's not that obvious that you have to use `extra = list(cleanup = F)`

**Comment by gaborcsardi** [comment]
Do you want to submit a PR?

**Comment by burgerga** [comment]
Sure! It will probably take me a couple of days to get to it though ;)

**Comment by gaborcsardi** [comment]
The docs have 
```r
#' * `extra`: List of extra arguments to pass to [processx::process].
```

So it seems that this is solved now.
