### ISSUE TITLE
Backgrounding a script in shiny while tracking Stderr/out without blocking

### ISSUE THREAD

**Issue by D3SL** [r-lib/callr#210]
I'm trying to execute a long-running job from a shiny app without blocking that session. I've seen this done with [Future](https://stackoverflow.com/questions/50165443/async-process-blocking-r-shiny-app) but I wanted to use some of CallR's features like `read_*`.

Unfortunately it seems like putting `return(NULL)` in the observer after starting the background job doesn't work for CallR the way it does for Future. Is there a different approach I can use? I've tried both `r_bg()` and `rscript_process` without success, I'm pretty sure the issue is the observer wanting to sit and wait for the background job.

```R
  ##Long running background job-----
  observeEvent(input$run_script_background,{
    reactivecontainer$background_job_ran<-TRUE
    options <- rscript_process_options(script = here("background_job_script.r"))
    reactivecontainer$bg_jobs$background_job<-rscript_process$new(options)
    
    return(NULL)
  })

##Render running stdout/stderr----------
output$bg_asr_stdout<-renderText({
  req(reactivecontainer$background_job_ran==TRUE)
  invalidateLater(30000,session)
  reactivecontainer$background_job_stdout<-c(reactivecontainer$background_job_stdout,reactivecontainer$bg_jobs$bg_asr_report$read_output_lines(n=-1))
  as.character(reactivecontainer$background_job_stdout)
  #reactivecontainer$background_job_stdout<-c(reactivecontainer$background_job_stdout,reactivecontainer$bg_test$read_output_lines(n=-1))
  
})

output$bg_asr_stderror<-renderText({
  req(reactivecontainer$background_job_ran==TRUE)
  invalidateLater(30000,session)
  reactivecontainer$background_job_stderror<-c(reactivecontainer$background_job_stderror,reactivecontainer$bg_jobs$bg_asr_report$read_error())
  #reactivecontainer$background_job_stderror<-c(reactivecontainer$background_job_stderror,reactivecontainer$bg_test$read_error())
})
```

**Comment by gaborcsardi** [comment]
> Unfortunately it seems like putting return(NULL) in the observer after starting the background job doesn't work for CallR the way it does for Future. 

Why, what happens?

**Comment by D3SL** [comment]
So I think I figured it out. I was trying to make a super-minimal reprex for this and found the reprex worked while the full app didn't, even though they're the same code copied and pasted. The *one* difference it took me a while to consider is that in the full app I have `renderText` set up to track and render the output of both stderr and stdout, but for the reprex I only copied stdout.

Something about trying to track and display the output of `bg$read_error()` using this method causes an indefinite hang of the parent app, the console will flood with `character(0)` (or `NULL` if you don't have it in `as.character()`). It works fine interactively but doesn't like being used this way.

I'm not sure if this is a bug or just user error on my part.

```
if (interactive()) {
library(shiny)
library(callr)
library(future.callr)

plan(callr)

ui <- fluidPage(
  tags$h2("Start test process"),
  tags$br(),
  actionButton(
    inputId = "bttn1",
    label = "Goodnight"
  ),
  tags$br(),
  textOutput(outputId = "bg_stdout"),
  textOutput(outputId = "bg_stderr"),
  actionButton(inputId="bttn2",label="click to test reactivity"),
  textOutput(outputId="reactivity_test")
)

server <- function(input, output, session) {
  reactivecontainer<-reactiveValues()
  reactivecontainer$bg_test_stdout<-"Awaiting stdout"
reactivecontainer$bg_test_stdout<-"Awaiting stderr"
  
  observeEvent(input$bttn1,{
    reactivecontainer$bg_test<-r_bg(function(){
      Sys.sleep(3)
      print("nap one")
      Sys.sleep(3)
      print("nap two")
      Sys.sleep(3)
      print("nap three")
      return("three sleeps done")
    })
  })

  output$bg_stdout <-renderText({
    invalidateLater(1000,session)
    reactivecontainer$bg_test_stdout<-c(reactivecontainer$bg_test_stdout,reactivecontainer$bg_test$read_output_lines(n=-1))
    as.character(reactivecontainer$bg_test_stdout)
    print(as.character(reactivecontainer$bg_test_stdout))
  })

  output$bg_stderr <-renderText({
    invalidateLater(1000,session)
    reactivecontainer$bg_test_stderr<-c(reactivecontainer$bg_test_stderr,reactivecontainer$bg_test$read_error())
    as.character(reactivecontainer$bg_test_stderr)
    print(as.character(reactivecontainer$bg_test_stderr))
  })

  output$reactivity_test<-renderText(input$bttn2)

}
shinyApp(ui = ui, server = server)
}
```

**Comment by gaborcsardi** [comment]
This gives me:

```r
Warning: Error in renderText: attempt to apply non-function
  96: renderText [/private/tmp/sh.R#48]
  95: func
  82: renderFunc
  81: output$bg_stderr
   1: shiny::runApp
```

Also, do you think you can create an example without future.callr? Just to simplify things, because I have no clue what future.callr does.

**Comment by D3SL** [comment]
That's just because `reactivecontainer$bg_test_stderr<-c(reactivecontainer$bg_test_stderr,reactivecontainer$bg_test$read_error())` kicks in immediately and there isn't a `bg_test` process until you click the first button, it's harmless. As for future.callr I'd thought it was required to use with Shiny but apparently not, you can just delete the library call and `plan(callr)` without any effect.

**Comment by D3SL** [comment]
Here, the same example as before but without the distractions. Reactivity works fine before clicking "Begin BG test", and everything will work fine if the `bg_test$read_error()` call is commented out, but if you try to read stderror the whole app freezes up permanently. Including `print(as.character(reactivecontainer$bg_test_stderr))` for diagnostics shows the console getting flooded with the empty output of `bg_test$read_error()`. Switching to `read_error_lines()` leads to everything working fine.

According to processx `read_error()` and `read_output()` are supposed to be non-blocking but it seems like what's happening is the app is latching onto `read_error()` and running it constantly. 

I'm closing this here since the root of this is processx, if it's even an issue at all rather than expected behavior. It would be helpful to add a note in callR's documentation to use `read_*_lines()` in shiny apps to avoid blocking/issues though.

```R
if (interactive()) {
  library(shiny)
  library(callr)
  
  ui <- fluidPage(
    tags$h2("Start test process"),
    tags$br(),
    actionButton(
      inputId = "bttn1",
      label = "Begin BG Test"
    ),
    tags$br(),
    textOutput(outputId = "bg_stdout"),
    textOutput(outputId = "bg_stderr"),
    actionButton(inputId="bttn2",label="click to test reactivity"),
    textOutput(outputId="reactivity_test")
  )
  
  server <- function(input, output, session) {
    reactivecontainer<-reactiveValues()
    reactivecontainer$bg_test_stdout<-"Awaiting stdout"
    reactivecontainer$bg_test_stdout<-"Awaiting stderr"
    reactivecontainer$ready<-FALSE
    
    observeEvent(input$bttn1,{
      reactivecontainer$ready<-TRUE
      reactivecontainer$bg_test<-r_bg(function(){
        Sys.sleep(3)
        print("nap one")
        Sys.sleep(3)
        print("nap two")
        Sys.sleep(3)
        print("nap three")
        return("three sleeps done")
      })
    })
    
    output$bg_stdout <-renderText({
      req(reactivecontainer$ready==TRUE)
      invalidateLater(1000,session)
      reactivecontainer$bg_test_stdout<-c(reactivecontainer$bg_test_stdout,reactivecontainer$bg_test$read_output_lines(n=-1))
      as.character(reactivecontainer$bg_test_stdout)
      print(as.character(reactivecontainer$bg_test_stdout))
    })
    
    output$bg_stderr <-renderText({
      req(reactivecontainer$ready==TRUE)
      invalidateLater(1000,session)
      reactivecontainer$bg_test_stderr<-c(reactivecontainer$bg_test_stderr,reactivecontainer$bg_test$read_error())
      as.character(reactivecontainer$bg_test_stderr)
      print(as.character(reactivecontainer$bg_test_stderr))
    })
    
    output$reactivity_test<-renderText(input$bttn2)
    
  }
  shinyApp(ui = ui, server = server)
}
```

**Comment by gaborcsardi** [comment]
> According to processx read_error() and read_output() are supposed to be non-blocking but it seems like what's happening is the app is latching onto read_error() and running it constantly.

`read_output()` and `read_error()` _are_ non-blocking, they return the empty string (`""`) here, because there is no output. 

I forgot the details of how reactivity worked in Shiny, but I think if you use `read_error()`, then you would want `paste0()` instead of `c()`:

```r
reactivecontainer$bg_test_stderr <- paste0(
  reactivecontainer$bg_test_stderr,
  reactivecontainer$bg_test$read_error()
)
```

Because `read_error()` returns empty string (`""`) if there is no output, so if you use `c()` then you get a longer character vector of empty strings, so `renderText()` will be called again and again.
