### ISSUE TITLE
Add on_status_change callback to `r_bg`?

### ISSUE THREAD

**Issue by vspinu** [r-lib/callr#217]
The easiest way I could think of checking for status change is in a `later` loop. Is there an easier way? 

I would presume that every consumer of `r_bg()` would need to pool for status one way or another. So maybe this functionality should be part of the `callr` or `processx` package proper?

**Comment by gaborcsardi** [comment]
You can poll, the function is called `processx::poll()`.

**Comment by vspinu** [comment]
I know, but then I still have to run it myself in a later loop for every process I create. Wouldn't it make sense for this to be handled automatically by the package?

**Comment by vspinu** [comment]
Yes, that's what I meant. 

Sure. I understand. Thanks!
