### ISSUE TITLE
Unhappy interaction between `pak::pkg_deps_explain()` and knitr

### ISSUE THREAD

**Issue by jennybc** [r-lib/callr#218]
I discovered this by trying to use `pak::pkg_deps_explain()` in a reprex. The expected pak output (the output I see interactively) does not show up.

I then removed reprex (the package) from the equation and tried to just knit `.R` and `.Rmd` containing just the command `pak::pkg_deps_explain()`.

That fails.

If the file `pak-mystery.Rmd` contains:

````
---
title: "pak mystery"
output: html_document
---

```{r}
pak::pkg_deps_explain("readxl", "cli")
```
````

Knitting it fails like so:

```
Quitting from lines 7-8 (pak-mystery.Rmd) 
Error in invokeRestart("muffleMessage") : 
  no 'restart' 'muffleMessage' found
Calls: <Anonymous> ... doWithOneRestart -> signalCondition -> <Anonymous> -> invokeRestart
```

and similarly for the `.R` case.

**Comment by gaborcsardi** [comment]
This was added here: https://github.com/r-lib/callr/commit/2a1a620f6bb706ebd8a1eb7060184da02c1e1d6d and seems that we can also use `muffleMessage`, so I'll add that patch.

Re. pak, this needs a new nightly build, so depending on how the new nightly build script works out it will be in devel pak in 1-2 days.
