### ISSUE TITLE
Consider not compressing the output

### ISSUE THREAD

**Issue by dfalbel** [r-lib/callr#222]
I wonder if it would be possible to not compress the results when saving outputs from the temporary R session here:

https://github.com/r-lib/callr/blob/b71a11a27ec0b979412ba501b2587960c1f63190/R/script.R#L104-L112

Just by adding `compress=FALSE` here we can get a very nice speedup, eg:

with the CRAN version:

```
> system.time({
+   callr::r(function() {runif(5e6)})  
+ })
   user  system elapsed 
  4.527   0.102   4.630 
```

with no compression:

```
> system.time({
+   callr::r(function() {runif(5e6)})  
+ })
   user  system elapsed 
  0.723   0.241   0.764 
```

**Comment by gaborcsardi** [comment]
Good idea.

**Comment by gaborcsardi** [comment]
I think the default should be `compress = FALSE` then, and we can have an option to turn it back on: `callr.compress_transport` or something like that. (IDK who would need that, but just in case.)

Do you want to submit a PR? (No pressure :)

**Comment by dfalbel** [comment]
Sure! I will submit a PR soon! 
Do you think we should also look for other `saveRDS` calls, eg when passing the function and arguments?

https://github.com/r-lib/callr/blob/ea5c3df7788e43870a265b276d3a4ae103e91557/R/setup.R#L17

**Comment by gaborcsardi** [comment]
Yeah, I guess the default and the option should apply to all of them.
