### ISSUE TITLE
`callr::r()` in {renv} project creates library in wrong location

### ISSUE THREAD

**Issue by AshesITR** [r-lib/callr#224]
When running, e.g., `callr::r(function() { getwd() })` from a project using {renv}, it initializes a new renv library at `project/dir/library` instead of using the library located at `project/dir/renv/library`.

I don't have a reprex at the moment, but let me know if you need one; it should be straightforward.

Also, `getwd()` is `project/dir` as expected so I don't know why `renv` tries to initialize in this weird location.

**Comment by gaborcsardi** [comment]
I cannot reproduce this.

**Comment by AshesITR** [comment]
Thanks for trying. I'll add a reprex asap.

**Comment by AshesITR** [comment]
Windows 10, R 4.1.2:

``` r
proj_dir <- tempfile("renv_callr_bug")
dir.create(proj_dir)

writeLines("library(lintr)", con = file.path(proj_dir, "sample.R"))
withr::with_dir(
  proj_dir,
  renv::init()
)
#> * Initializing project ...
#> * Discovering package dependencies ... Done!
#> * Copying packages into the cache ... Done!
#> * Lockfile written to 'C:/Users/ag06446/AppData/Local/Temp/RtmpmgfT5x/renv_callr_bug1a9c495a12ae/renv.lock'.

list.dirs(proj_dir, recursive = FALSE, full.names = FALSE)
#> [1] "renv"

withr::with_dir(
  proj_dir,
  callr::r(function() getwd())
)
#> [1] "C:/Users/ag06446/AppData/Local/Temp/RtmpmgfT5x/renv_callr_bug1a9c495a12ae"

list.dirs(proj_dir, recursive = FALSE, full.names = FALSE)
#> [1] "library" "renv"

unlink(proj_dir, recursive = TRUE)
```

<sup>Created on 2022-04-07 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by gaborcsardi** [comment]
Still cannot reproduce it, unfortunately. 

```r
> packageVersion("callr")
[1] '3.7.0'
> packageVersion("renv")
[1] '0.15.4'
```
