### ISSUE TITLE
rsession$new() fails when loading my .Rprofile is too long

### ISSUE THREAD

**Issue by statquant** [r-lib/callr#226]
Hello, I have the following issue:
- when I have a .Rprofile is the root directory if the `.Rprofile` takes too long to source `r_session$new()` crashes

**pseudo repex**
```
$ mkdir callr_bug
$ cd callr_bug
```
_long .Rprofile to load_
```
$ echo "Sys.sleep(10)" > .Rprofile
$ R --vanilla
> library(callr)
> rs <- r_session$new()
stdout:]
stderr:] 
Error in rs_init(self, private, super, options, wait, wait_timeout) :
  Could not start R session, timed out
Type .Last.error.trace to see where the error occurred
> q()
```
_short .Rprofile to load_
```
$ echo "Sys.sleep(1)" > .Rprofile
$ R --vanilla
> library(callr)
> rs <- r_session$new()
# worked !
> q()
```

I think you're supposed to be able to play with `r_session_options()` to not load `.Rprofile` but it does not work for me
I tried
- r_session_options(user_profile = FALSE, system_profile = FALSE, cmdargs = "--vanilla") nothing worked

Can I suggest allowing the user to pass timeout ? that's probably best the user can load his .Rprofile even if that's long ?

**Comment by gaborcsardi** [comment]
This works for me:

```r
rs <- r_session$new(wait_time = 15 * 1000)
```

**Comment by statquant** [comment]
Indeed, works for me too, I missed this params.
But shouldn't the options have worked as well?
