### ISSUE TITLE
Show = TRUE without duplicated error message

### ISSUE THREAD

**Issue by wlandau** [r-lib/callr#231]
The output of [`targets`](https://docs.ropensci.org/targets/) can get verbose if there is a user error. I would like to keep printing progress messages to the console using a default `show = TRUE` in `callr::r()`, but if there is an error, I would like to only print the error message once (especially for long messages). Is there a way to do this in `callr`?

``` r
callr::r(
  function() {
    message("useful info")
    stop("really long error message", call. = FALSE)
  },
  show = TRUE
)
#> useful info
#> Error : really long error message
#> Error: callr subprocess failed: really long error message
```

<sup>Created on 2022-08-07 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

A couple other things that could be convenient to address:

* There is an extra space between "Error" and ":" in "Error : really long error message".
* It would be great to optionally omit "callr subprocess failed" (as opposed to a potentially less reliable `gsub()` on the output on my end)

**Comment by gaborcsardi** [comment]
This is how this looks for me:
```
❯ callr::r(
+   function() {
+     message("useful info")
+     stop("really long error message", call. = FALSE)
+   },
+   show = TRUE
+ )
useful info
Error : really long error message
Error:
! error in callr subprocess
Caused by error:
! really long error message
Type .Last.error to see the more details.
```

This is hard to make less verbose in callr, without restricting certain use cases because we cannot be sure that the first error message reaches the user. We would also lose the stack traces.

If you don't want to show the last error message, then you can catch it, maybe and throw a different error. You'll probably lose the stack trace, though.

Another solution is to avoid printing error messages in the subprocess. E.g.

```r
callr::r(
  function() {
    options(show.error.messages = FALSE)
    message("useful info")
    stop("really long error message", call. = FALSE)
  },
  show = TRUE
)
```

will produce

```
useful info
Error:
! error in callr subprocess
Caused by error:
! really long error message
Type .Last.error to see the more details.
```

**Comment by wlandau** [comment]
Thanks @gaborcsardi, I did not know about the `show.error.messages` option. And yes, I can avoid the "error in callr subprocess" message by catching the error in the subprocess and returning the condition object.
