### ISSUE TITLE
Subscript out of bounds error

### ISSUE THREAD

**Issue by billdenney** [r-lib/callr#235]
When trying to setup GitHub actions so that a set of GitHub packages would be used for CI instead of the CRAN version, I'm getting an error that I think may be a callr error (though honestly, I'm not sure what the source of the issue is):

https://github.com/nlmixr2/nlmixr2lib/actions/runs/3130187415/jobs/5080149741#step:5:6627

I believe that it is coming from here:

https://github.com/nlmixr2/nlmixr2lib/blob/44a18f5b44c2cab438d77d27651a11eee383fa15/.github/workflows/test-coverage.yaml#L29-L39

**Comment by gaborcsardi** [comment]
I think is is fixed in the devel version of pak, try adding `pak-version: devel` to the `setup-r-dependencies` step.

**Comment by billdenney** [comment]
Thanks!  That fixed it.
