### ISSUE TITLE
ignoring sigpipe signal

### ISSUE THREAD

**Issue by sm2607** [r-lib/callr#244]
Hi I am using r_bg, function for background processing in Rshiny, its working fine according to requirement,  but sometime it fails with below error:

`cat(conditionMessage(c), file = stderr(), sep = ""): ignoring SIGPIPE signal`

While when we try again with same parameters, it ran successfully.

**Comment by gaborcsardi** [comment]
Can you show the code that you are running?

**Comment by sm2607** [comment]
its a big code, not possible to share. Also, not able to create minimum reproducible example, because some times this  error appear and some time code ran successfully. 
My function contains tryCatch, which I ran through r_bg function
