### ISSUE TITLE
How do I pass object back to main session from `r_bg`. 

### ISSUE THREAD

**Issue by shahr43** [r-lib/callr#257]
Cross posting from SO : https://stackoverflow.com/questions/76950908/how-to-set-shiny-outputs-from-inside-the-function-when-using-callrr-bg

```
library(shiny)

ui <- fluidPage(
  actionButton("click", "click me!"),
  textOutput("text")
)

server <- function(input, output, session) {
  rv <- reactiveValues(callr = NULL)
  
  call_fun <- function(input, output) {
    Sys.sleep(5)
    output$text <- shiny::renderText("Output is generated")
  }
  
  observeEvent(input$click, {
    rv$callr <- callr::r_bg(function(input, output, call_fun) call_fun(input, output), 
                  args = list(input, output, call_fun))
  })
  
  observe({
    req(rv$callr)
    cat('\nIn Observe')
    if(rv$callr$is_alive()) {
      invalidateLater(millis = 1000, session = session)
      cat('\nProcessing')
    }
    else {
      cat("\nDone")
    }
  })
  
}

shinyApp(ui, server)
```

I cannot see the `text` in the output after the process finishes.

**Comment by gaborcsardi** [comment]
I am not sure what your question is. 

The manual shows how to get an object back when the process is done:
```r
     rx <- r_bg(function() 1 + 2)

     # wait until it is done
     rx$wait()
     rx$is_alive()
     rx$get_result()
```

> ```
>   call_fun <- function(input, output) {
>     Sys.sleep(5)
>     output$text <- shiny::renderText("Output is generated")
>   }
> ```

I don't think that you can call `shiny::renderText()` in the background process, AFAIK shiny cannot communicate from one process to another.

**Comment by gaborcsardi** [comment]
I am going to close this, as there seems to be nothing actionable on my side. Please reopen if you think you still have issues.
