### ISSUE TITLE
Reset non-set environment variables

### ISSUE THREAD

**Issue by king-of-poppk** [r-lib/callr#259]
Currently `callr`'s logic is to only unset variables that are explicitly listed as `NA` (and I guess the empty string to some extent), see here:

https://github.com/r-lib/callr/blob/e3e0acffdd817bb1c0f7fc5054f93b1d65ed8a45/R/utils.R#L57-L58

Would it make sense to have a way to start from a clean environment? Perhaps one that has the minimal set of env vars that make it possible to start `R -f`? Might be platform-dependent.

**Comment by gaborcsardi** [comment]
That would be very fragile, as it is not clean what versions of what platforms need which env vars.

It would also be a breaking change, as existing code might rely on the inheritance of environment variables.

Nevertheless, if you want to do that, you can, by setting (nearly?) all existing env vars to `NA`.

**Comment by king-of-poppk** [comment]
So if one wants to do that manually, they just wrap `callr` with a variant of the `set(temporary); callr(...); set(previous)` dance?

**Comment by gaborcsardi** [comment]
No, you can use the `env` argument:

```r
❯ Sys.setenv("FOO" = "bar")

❯ callr::r(function() Sys.getenv("FOO"))
[1] "bar"

❯ callr::r(function() Sys.getenv("FOO"), env = c(FOO = NA_character_))
[1] ""
```

**Comment by gaborcsardi** [comment]
Yes, if you want to start with a clean environment, set all current env vars to `NA` in the `env` argument.

**Comment by king-of-poppk** [comment]
I guess since both `Sys.unsetenv` and `callr`'s `env` parameter require explicit listing of the existing variables to "unset" it is only a question of API stability.

**Comment by gaborcsardi** [comment]
No, do not use `Sys.unsetenv()`, that's not a good solution. R is single threaded, but occasionally there is a async code execution, e.g. finalizers might be triggered by the garbage collector, and they may use env vars. 

Plus, callr's machinery might use env vars as well, so if you unset them before calling callr, then you might change callr's behavior.

**Comment by king-of-poppk** [comment]
Good point!
