### ISSUE TITLE
To what extent is `callr::r_safe` safe?

### ISSUE THREAD

**Issue by king-of-poppk** [r-lib/callr#261]
From experience, code evaluated with `callr::r_safe` can read environment variables from `/proc/*/environ`, and modify the files `${TMPDIR}/<random>/callr-client--<version>.so` and `${TMPDIR}/<random>/callr-env-<random>` which enables hijacking other evaluation sessions. The serialized input and output files of other sessions can also be read provided `callr::r_safe` is run in parallel (or that those files are not properly cleaned up).

What does `safe` mean in `callr::r_safe`?

**Comment by gaborcsardi** [comment]
It is in the documentation, see `?calle::r_safe`. It is a completely different definition of safe, I am afraid.
