### ISSUE TITLE
Alternative to `arch` argument with `callr` v3.3.2

### ISSUE THREAD

**Issue by king-of-poppk** [r-lib/callr#268]
Is there an alternative to the `arch` argument of `callr::r` before `v3.6.0`? Specifically for `v3.3.2` where the intended goal is to wrap the `R` executable with `unshare`/`chroot`/`capsh`.

**Comment by gaborcsardi** [comment]
AFAICT there isn't, only with recent versions.

**Comment by gaborcsardi** [comment]
Not much we can do about older callr releases, so I am closing this.
