### ISSUE TITLE
How to detect failure in `r_bg()` ?

### ISSUE THREAD

**Issue by krlmlr** [r-lib/callr#270]
`get_exit_status()` doesn't seem to be useful:

``` r
p <- callr::r_bg(function() stop(), error = "error")
p$wait()
p$get_exit_status()
#> [1] 0
writeLines(p$read_all_error_lines())
#> Error in (function ()  :
```

<sup>Created on 2024-01-18 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by gaborcsardi** [comment]
Call `p$get_result()` and it'll throw a `callr_status_error` if there was an error in the subprocess.
