### ISSUE TITLE
Rtmp files left in /tmp directory with VSCode

### ISSUE THREAD

**Issue by tabulez** [r-lib/callr#277]
Related to this issue https://github.com/r-lib/callr/issues/104. I previously posted about this issue here https://github.com/REditorSupport/vscode-R/issues/1486 and in the callr closed thread so apologies about the redundancy!

I'm noticing this issue in the context of using vscode-R on a linux server. When VSCode is closed without formally quitting R or disconnecting from the server, Rtmp directories remain. Thanks for any help on resolving this!

**To Reproduce**
- SSH into a remote server via putty and remove any existing Rtmp directories
- With vscode, open test.R that has the line: print("hello world")
- Close vscode after running the line. I noticed two new Rtmp directories in /tmp that remained.
- In putty, run R, print("hello world") q(). No new Rtmp directories were added. Same happens if I use "Rscript test.R"
- If I repeat step 2, I notice 2 new directories in /tmp are created that aren't removed after closing vscode.

**Output**
- The files and directories generated in the example look like this: 
```
./RtmpkpecfE:
total 334K
callr-client--eff06ee.so
callr-env-4e74108faaf5
callr-fun-4e747d5c0b79
callr-res-4e7435f83e09
callr-scr-4e74584134a4
callr-sev-4e742c3c1549
callr-sev-4e744c22c3
callr-sev-4e744d2e7ca0
callr-sev-4e74531de39e
callr-sev-4e7463f7c62a
callr-spr-4e7418ba6840
callr-spr-4e741d41d3da
callr-spr-4e74606cd5c9
callr-spr-4e74748293fd
callr-spr-4e74c871bcd
callr-uev-4e74316db898
callr-uev-4e74480eebcf
callr-uev-4e74503ac808
callr-uev-4e74a9da0d6
callr-uev-4e74d3cfc3d
callr-upr-4e7418eb6e65
callr-upr-4e74433f3810
callr-upr-4e744509737a
callr-upr-4e74692e206a
callr-upr-4e74f103836

./RtmpwTGjlB:
total 83K
libloc_180_124706c06bfefeeb.rds
libloc_180_dbd70c741b94b12c.rds
libloc_215_684dcd0b7abed33c.rds
```

**Environment**
- OS: Linux CentOS 7
- VSCode Version: 1.86
- R Version: 3.6.0
- vscode-R version: 2.8.2
- language server version = 0.3.16
- callr = 3.7.3

**Comment by gaborcsardi** [comment]
If the R process is killed, then it has no chance to clean up temporary files. I suggest you use some system tool to periodically clean up old files in the system temporary directory. FWIW this is the default on many Linux systems.

**Comment by tabulez** [comment]
Thanks, I'll work to get something like that implemented. I currently have users edit their .Renviron file with a new TMPDIR location so clean-up can be managed per user. Do you foresee any issues managing it that way?
