### ISSUE TITLE
How to use customize functions in the `func` function?

### ISSUE THREAD

**Issue by evanliu3594** [r-lib/callr#278]
Hi, I'm new to `callr`, recently I was trying to run some expr in `callr` in shinyApp, but I can't find a way to quote customized functions.

for example: 
```
add_1 <- \(x) return(x + 1)

loop_x <- function(){
  i <- 1
  while(TRUE) {
    i = add_1(i)
    readr::write_lines(i, "./data/x.txt")
    Sys.sleep(1)
  }
}

rtask <- callr::r(loop_x)
```
won't work, but when put when put `add_1` into `func` function, it works fine.

```
loop_x <- function(){
  i <- 1
  add_1 <- \(x) return(x + 1)
  while(TRUE) {
    i = add_1(i)
    readr::write_lines(i, "./data/x.txt")
    Sys.sleep(1)
  }
}

rtask <- callr::r(loop_x)
```

Is there any simple way solving this? modifying the `package` argument seems not help.

I'm having many customized functions to quote, it is almost impossible to put them all in the `func` function.

**Comment by gaborcsardi** [comment]
I am not sure what you mean by "quote". You mean you want to call other functions from the same package? Then yes, use the `package` argument.

**Comment by evanliu3594** [comment]
> I am not sure what you mean by "quote". You mean you want to call other functions from the same package? Then yes, use the `package` argument.

yes, just use functions in the Global Environment, but `callr` says "could not find function"
```
> add_1 <- \(x) return(x+1)
> loop_x <- function(){
+   i <- 1
+   while(TRUE) {
+     i = add_1(i)
+     readr::write_lines(i, "./data/x.txt")
+     Sys.sleep(1)
+   }
+ }
> rtask <- r(loop_x)
Error: 
! in callr subprocess.
Caused by error in `add_1(i)`:
! could not find function "add_1"
Type .Last.error to see the more details.
```
in this case, I think the `add_1` function is stored in the `.GlobalEnv`, where `package` argument by default directed to?

**Comment by evanliu3594** [comment]
Thanks for your patient explain! Now I understand why the global environment functions can't be read. 
And your solution is quite inspiring, I almost forgot that functions can be put into a `list()` 😀
