### ISSUE TITLE
how to get out of session$attach()

### ISSUE THREAD

**Issue by venpopov** [r-lib/callr#281]
I ran this code:

```r
library(callr)
sess <- r_session$new()
sess$attach()
```

which opened an interactive console within the external session. I tested a bit, and typed q() to exist it, which I guess was a mistake, as now my console is completely non-responsive:

```r
> sess$attach()
RS 1018860 > ls()
character(0)
RS 1018860 > a = 1
RS 1018860 > ls()
[1] "a"
RS 1018860 > 
RS 1018860 > q
function (save = "default", status = 0, runLast = TRUE) 
.Internal(quit(save, status, runLast))
<bytecode: 0x55b1affd2158>
<environment: namespace:base>
RS 1018860 > q()
fsdf
1
exit
q
```

Two questions:
- How do you get out of a console from a session you attached (in general)?
- In this case, after having typed q() and my console is unresponsive, what can I do to get back to my original session and console? I am currently running a few background jobs in this Rstudio session, so if I restart the session I will loose the jobs (they've been running for 40ish hours...)

**Comment by gaborcsardi** [comment]
> How do you get out of a console from a session you attached (in general)?

Press CTRL+C, or the stop button in RStudio.

> In this case, after having typed q() and my console is unresponsive, what can I do to get back to my original session and console? I am currently running a few background jobs in this Rstudio session, so if I restart the session I will loose the jobs (they've been running for 40ish hours...)

Press CTRL+C, or the stop button in RStudio.

**Comment by venpopov** [comment]
Neither of these work. There is no red button like usual and ctrl+c has no
effect unf3

**Comment by venpopov** [comment]
If it's relevant, this is in rstudioserver via a browser

**Comment by gaborcsardi** [comment]
Try pressing `ESC` while the console is active. How do you usually interrupt a command?
