### ISSUE TITLE
r_process subclass shouldn't be cloneable

### ISSUE THREAD

**Issue by ElianHugh** [r-lib/callr#284]
Since upgrading to R 4.4, I've been having a warning pop up every time I try to use `callr::r_bg`. I suspect it's a result of me updating R6 -- perhaps a change in R6 at some point changed cloning rules or warning behaviour? 

``` r
callr::r_bg(\() {})
#> Superclass process has cloneable=FALSE, but subclass r_process has cloneable=TRUE. A subclass cannot be cloneable when its superclass is not cloneable, so cloning will be disabled for r_process.
#> PROCESS 'R', running, pid 187359.
```

<sup>Created on 2024-06-04 with [reprex v2.1.0.9000](https://reprex.tidyverse.org)</sup>

Very small bug, but it can be annoying when logging or testing to be spammed with the R6 warning. I think the solution would be to change the `r_process` class to explicitly say `cloneable=FALSE`, though I'm surprised that cloning behaviour isn't implicitly inherited.

**Comment by gaborcsardi** [comment]
I don't think this happens with the released version of R6, but yeah, we should change it.
