### ISSUE TITLE
Confused about s3 dispatch in r_safe

### ISSUE THREAD

**Issue by nbenn** [r-lib/callr#33]
I'm not sure if this qualifies as a bug, but I don't understand what's happening here. Consider the following code snippet:

```r
callr::r_safe(
  function(n) {
    point <- function(x, y) {
      stopifnot(is.numeric(x), is.numeric(y))
      structure(list(x = x, y = y), class = "point")
    }

    abs.point <- function(x) {
      sqrt(x$x ^ 2 + x$y ^ 2)
    }

    points <- mapply(point, runif(n), runif(n), SIMPLIFY = FALSE)

    sapply(points, abs)
  },
  args = list(n = 5L)
)
```

If `abs.point` is called as `abs(points[[1]])`, it works as I would expect. But using `sapply` to iterate, I get a `non-numeric argument to mathematical function` error.

The actual problem I'm facing is that something along the lines of the above example is being used in an rmarkdown document and pkgdown uses `r_safe` to knit the `.Rmd` file.

**Comment by gaborcsardi** [comment]
This is not a `callr` issue. It is an S3 method lookup issue. E.g. this fails the same way:

```
f <- function(n) {
  point <- function(x, y) {
    stopifnot(is.numeric(x), is.numeric(y))
    structure(list(x = x, y = y), class = "point")
  }

  abs.point <- function(x) {
    sqrt(x$x ^ 2 + x$y ^ 2)
  }

  points <- mapply(point, runif(n), runif(n), SIMPLIFY = FALSE)

  sapply(points, abs)
}
f(10)
#> Error in FUN(X[[i]], ...) : non-numeric argument to mathematical function
```

I think it is a bug in base R, but R-core devs might not share this opinion. One workaround is to put the S3 method definition into `.GlobalEnv` (i.e. outside of a function in the Rmd for you).

**Comment by nbenn** [comment]
Thanks for the quick feedback.

Sorry to insist. Do you also not consider this a bug in my original scenario? There I did not have my s3 method definition wrapped in a function. My knitr code chunk is something like

```r
point <- function(x, y) {
  stopifnot(is.numeric(x), is.numeric(y))
  structure(list(x = x, y = y), class = "point")
}

abs.point <- function(x) {
  sqrt(x$x ^ 2 + x$y ^ 2)
}

points <- mapply(point, runif(5), runif(5), SIMPLIFY = FALSE)

sapply(points, abs)
```

When I create my `.md` using `rmarkdown::render`, all is fine. However pkgdown wraps `render` with `r_safe`, which causes the markdown generation to fail. If you agree that something seems off, I will open an issue at pkgdown.

**Comment by gaborcsardi** [comment]
`rmarkdown::render` evaluates code in an empty environment by default and this messes up the S3 lookup as well. You can set its `envir` argument to `.GlobalEnv` to work around this. This is done here: https://github.com/r-lib/pkgdown/blob/d4e9509f99265a551f03ef2696d2f0393f24103c/R/build-articles.R#L114-L123

But it is not done here:
https://github.com/r-lib/pkgdown/blob/c8726f9242b2b67f572c16422c83cdc8160c7628/R/build-home.R#L72-L79

So maybe the latter is biting you, and then yes, this needs a fix in `pkgbuild`.

**Comment by nbenn** [comment]
Thanks for getting back to me.
