### ISSUE TITLE
New CRAN release

### ISSUE THREAD

**Issue by randy3k** [r-lib/callr#35]
The last release was published about 2 years ago. Is there any plan to publish a new release? It is such a great tool to enhance R performance and flexibility.

**Comment by gaborcsardi** [comment]
First we need to update `processx` on CRAN, and this has been taking more than half a year now.

**Comment by randy3k** [comment]
Does callr@master require the newest processx at all? I have a package which depends on the current master.

**Comment by gaborcsardi** [comment]
Yes, for some features, e.g. background R processes and timeouts.

**Comment by randy3k** [comment]
It seems the `callr@master` is running just fine with the released `processx v2.0.0.1`. I tried both `r_bg` and `r(..., timeout = ..)`. So I guess `processx` should not stop a new release of `callr`?

**Comment by gaborcsardi** [comment]
Maybe you are right. Still, the new `processx` version has a lot of bug fixes, so ideally, it should be on CRAN before we rely on it in `callr`.

**Comment by randy3k** [comment]
Great. I see that a new version has released.
