### ISSUE TITLE
Fails on install for windows

### ISSUE THREAD

**Issue by rwatts3** [r-lib/callr#36]
Greetings, 

I am installing a package that uses @master as a dependency. 
After attempting to install both via the package, as well as directly the installation fails on windows 7

Specifically "make -f "Makevars.win"

**Comment by gaborcsardi** [comment]
I am sorry, I don't understand. What is the code that you used, and what is the output?

**Comment by rwatts3** [comment]
I believe I may have solved the issue. I didn't have Rtools installed, and therefore upon installing compilation failed.
