### ISSUE TITLE
Error in process_kill(self, private, grace) :    process_kill: Operation not permitted

### ISSUE THREAD

**Issue by wch** [r-lib/callr#46]
When I run the following repeatedly:

```R
p <- process$new('ls')
p$kill()
```

This error occasionally comes up:

```
> p <- process$new('ls')
> p$kill()
[1] TRUE
> p <- process$new('ls')
> p$kill()
[1] FALSE
> p <- process$new('ls')
> p$kill()
Error in process_kill(self, private, grace) : 
  process_kill: Operation not permitted
> p <- process$new('ls')
> p$kill()
[1] FALSE
```

Could this be due to a race where the process stops after the R function `process_kill()` is called, but before the C function `callr_kill` gets to the part where it does stuff with the process?

*****

In Travis logs, I also see `callr_kill: No child processes`. I haven't figured out how to reproduce it locally, but I suspect it has a similar cause.

```
Error in process_signal(self, private, signal) : 
  callr_get_exit_status: No child processes
Calls: <Anonymous> ... <Anonymous> -> sd_stop -> <Anonymous> -> process_signal
Error in process_kill(self, private, grace) : 
  callr_kill: No child processes
```

https://travis-ci.org/rstudio/shinytest/jobs/359462139#L3125-L3130

**Comment by wch** [comment]
It might be the case that it's impossible to avoid a race here. If so, I think it would be best not to throw an R error.

**Comment by gaborcsardi** [comment]
Why can't I reproduce this? Can you please show session info?

**Comment by wch** [comment]
```
─ Session info ───────────────────────────────────────────────────────────────────
 setting  value                       
 version  R version 3.4.3 (2017-11-30)
 os       macOS High Sierra 10.13.3   
 system   x86_64, darwin15.6.0        
 ui       RStudio                     
 language (EN)                        
 collate  en_US.UTF-8                 
 tz       America/Chicago             
 date     2018-03-28                  

─ Packages ───────────────────────────────────────────────────────────────────────
 package     * version    date       source                              
 assertthat    0.2.0      2017-04-11 CRAN (R 3.4.0)                      
 callr       * 2.0.2.9002 2018-03-26 Github (r-lib/callr@f981a0b)        
 clisymbols    1.2.0      2017-05-21 CRAN (R 3.4.0)                      
 crayon        1.3.4      2017-09-16 CRAN (R 3.4.1)                      
 debugme       1.1.0.9000 2018-01-15 Github (gaborcsardi/debugme@f4a116a)
 R6            2.2.2      2017-06-17 CRAN (R 3.4.0)                      
 rstudioapi    0.7        2017-09-07 CRAN (R 3.4.1)                      
 sessioninfo   1.0.0      2017-06-21 CRAN (R 3.4.1)                      
 withr         2.1.2      2018-03-15 CRAN (R 3.4.4)                      
 yaml          2.1.18     2018-03-08 CRAN (R 3.4.4)                      
```

**Comment by gaborcsardi** [comment]
So this does not fail for me in a new session:
```
for (i in 1:1000) { p <- process$new('ls'); p$kill() }
```

**Comment by gaborcsardi** [comment]
Does this fail for you? If not, is there another good way to make it fail?

**Comment by gaborcsardi** [comment]
So it does fail for you both in Linux and macOS, right?

**Comment by gaborcsardi** [comment]
Aha, got it: 
```
❯ sapply(1:100, function(x) { p <- process$new("ls", "/"); Sys.sleep(0.002); p$kill() })
Error in process_kill(self, private, grace) :
  process_kill: Operation not permitted
```

**Comment by gaborcsardi** [comment]
So this is coming from here:
https://github.com/r-lib/callr/blob/f981a0b3172b34ec5d6103a0bcb30fce760d9d94/src/unix/callr.c#L701

According to the manual:
```
kill() will fail and no signal will be sent if:

[EINVAL] Sig is not a valid, supported signal number.

[EPERM]  The sending process is not the super-user and its effective user id does not match the effec-
         tive user-id of the receiving process.  When signaling a process group, this error is
         returned if any members of the group could not be signaled.

[ESRCH]  No process or process group can be found corresponding to that specified by pid.

[ESRCH]  The process id was given as 0, but the sending process does not have a process group.
```

so this why I handle `ESRCH` specially, to avoid throwing an R error. The `EPERM` return value is bit unexpected, to be honest, but it is what it is.... I'll just handle that specially as well...

**Comment by gaborcsardi** [comment]
Please check if the fix works for you, it should, it looks  good here: 
```r
❯ sapply(1:100, function(x) { p <- process$new("ls", "/"); Sys.sleep(0.0015); p$kill() })
  [1]  TRUE  TRUE  TRUE  TRUE FALSE  TRUE  TRUE FALSE  TRUE  TRUE FALSE  TRUE
 [13] FALSE FALSE FALSE  TRUE  TRUE FALSE  TRUE FALSE  TRUE  TRUE FALSE  TRUE
 [25] FALSE  TRUE  TRUE FALSE  TRUE FALSE  TRUE FALSE  TRUE  TRUE  TRUE FALSE
 [37]  TRUE  TRUE FALSE  TRUE  TRUE FALSE  TRUE FALSE  TRUE  TRUE FALSE  TRUE
 [49]  TRUE FALSE  TRUE FALSE  TRUE FALSE  TRUE  TRUE FALSE  TRUE  TRUE  TRUE
 [61]  TRUE FALSE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE FALSE  TRUE FALSE
 [73]  TRUE  TRUE FALSE FALSE  TRUE  TRUE FALSE FALSE  TRUE  TRUE  TRUE  TRUE
 [85]  TRUE FALSE FALSE  TRUE  TRUE FALSE  TRUE FALSE  TRUE  TRUE FALSE  TRUE
 [97] FALSE  TRUE FALSE  TRUE
```

**Comment by wch** [comment]
Your computer must be faster than mine. :)

The fix does look like it worked -- I no longer see the error message.

This doesn't fix the other error I was seeing from Travis, which I believe was from here:
  https://github.com/r-lib/callr/blob/9c3882700d43e42604e0761f7a0f58bdf7d1d96f/src/unix/callr.c#L690

**Comment by wch** [comment]
From what I can find, the problem is that the process is reaped before `waitpid()` is called. https://stackoverflow.com/a/19249944/412655

My guess is that this is more likely to happen on Travis because the machines tend to be slow and bogged down with a lot other processes.

I've tried to repro the error with the following, but haven't succeeded:

```R
p <- process$new('ls')
# Wait for a long while
.Call(callr:::c_callr_kill, p$.__enclos_env__$private$status, 0.1)
```

**Comment by gaborcsardi** [comment]
Oops, sorry I missed that it was a different issue.

Good thing I forgot to update the error message, now we know which one is which..... I'll fix that in a sec as well....

**Comment by gaborcsardi** [comment]
Yeah, so this one is more difficult, because it seems to me that that error can only happen if another package overwrites our signal handler.

The `parallel` package does that for fork clusters for example. `httpuv` has a `sigaction` call: https://github.com/rstudio/httpuv/blob/2bf07cce242253097745ba6d084fd215627c88e5/src/libuv/src/unix/signal.c#L222 
Is  that ever executed? Probably not, because it would lead to more severe problems...

**Comment by gaborcsardi** [comment]
Looks like it is not executed, good. I wonder which package it could be then..... but  anyway, this is something that callr needs to sort out somehow.....

**Comment by gaborcsardi** [comment]
Btw. can you reproduce the Travis  error somehow?

**Comment by wch** [comment]
I still haven't been able to reproduce the Travis error locally.

Here's another test log that shows it. I noticed that there's also `callr_get_exit_status: No child processes` :
https://travis-ci.org/rstudio/shinytest/jobs/359456469#L3078-L3083

```
 Error in process_signal(self, private, signal) : 
    callr_get_exit_status: No child processes
  Calls: <Anonymous> ... <Anonymous> -> sd_stop -> <Anonymous> -> process_signal -> .Call
  Error in process_kill(self, private, grace) : 
    callr_kill: No child processes
  Calls: <Anonymous> ... <Anonymous> -> sd_stop -> <Anonymous> -> process_kill -> .Call
```

**Comment by gaborcsardi** [comment]
Yeah, both of these functions assume that the exit code was either not collected yet (via wait or waitpid), or it was collected by us.

It is interesting, though that they seem to come in pairs... I think I  can fix this, at some level. The exit code might be lost forever in this case, but we don't have to error, I'll just set it to NA.

**Comment by wch** [comment]
FWIW, I think the pairs were just a coincidence. Here's a case where it was just one:
https://travis-ci.org/rstudio/shinytest/jobs/359576507#L1225-L1227

**Comment by gaborcsardi** [comment]
OK, that makes sense.
