### ISSUE TITLE
Setting R_LIBS_USER to nonexistant file breaks R CMD build in R <= 3.3

### ISSUE THREAD

**Issue by krlmlr** [r-lib/callr#55]
From a Travis CI session with R 3.3:

```
$ R_LIBS_USER=/dummy R CMD build .                  
* checking for file ‘./DESCRIPTION’ ... OK
* preparing ‘dplyr’:
* checking DESCRIPTION meta-information ... OK
* cleaning src
Error in loadVignetteBuilder(pkgdir, TRUE) : 
  vignette builder 'knitr' not found
Execution halted
```

The command works if omitting the `R_LIBS_USER` override. I believe this triggers https://github.com/r-lib/styler/issues/46.

**Comment by gaborcsardi** [comment]
I believe callr sets the library path to the same as in the calling R process. Can you try to reproduce  with callr?

**Comment by krlmlr** [comment]
*callr* seems to set the `R_LIBS_*` variables to a nonexistent dummy file, like in this example. Still working on replicating it locally.

**Comment by gaborcsardi** [comment]
Yes, but it also sets the library path from the R profile.... maybe the profile is sometimes ignored?

**Comment by gaborcsardi** [comment]
> I'm very sorry...

No, thanks for creating the reprex!

I guess for building a vignette, R starts another R process, and that does not inherit the library path properly. We can just set  R_LIBS_USER as well, and also create a fake .Renviron file.

It is relatively easy to call an R process with the same config, but to make sure that the other R processes started from that (not via callr)  have the same config, now that is quite challanging....

**Comment by krlmlr** [comment]
Thanks for looking into it. Sorry for throwing these meta³ problems on you, unless of course you enjoy solving them ;-)

**Comment by gaborcsardi** [comment]
Can you pls  try with the latest master?

**Comment by krlmlr** [comment]
Test-driving now, will comment if anything suspicious pops up.
