### ISSUE TITLE
Site library paths go missing when changing the library path

### ISSUE THREAD

**Issue by glin** [r-lib/callr#58]
When changing the library path with `.libPaths()`, the site library paths disappear:

```r
callr::r(function() .libPaths())
## [1] "/usr/local/lib/R/site-library" "/usr/lib/R/site-library"      
## [3] "/usr/lib/R/library"           

callr::r(function() {
  .libPaths(tempdir())
  .libPaths()
})
## [1] "/tmp/RtmplLBE1z"    "/usr/lib/R/library"

callr::r(function() Sys.getenv("R_LIBS_SITE"))
## [1] "/tmp/RtmpC00eG2/file41e2d104715"
```

I'm not sure if this is intended, but I was expecting to see:

```r
.libPaths()
## [1] "/usr/local/lib/R/site-library" "/usr/lib/R/site-library"
## [3] "/usr/lib/R/library"

.libPaths(tempdir())
.libPaths()
## [1] "/tmp/RtmpCo52Xn"               "/usr/local/lib/R/site-library"
## [3] "/usr/lib/R/site-library"       "/usr/lib/R/library"

Sys.getenv("R_LIBS_SITE") 
## [1] "/usr/local/lib/R/site-library:/usr/lib/R/site-library:/usr/lib/R/library"
```

This was also the behavior in `callr::r` before https://github.com/r-lib/callr/commit/ffa393fda4ee73b2d99f92a90217e21c77a85bb2. The change seems to come from callr now setting `R_LIBS_SITE` to a temp file. The site library paths are inherited fine, but are lost when `.libPaths()` constructs new library paths.

**Comment by gaborcsardi** [comment]
Thanks! It is a bug indeed, will fix asap.

**Comment by gaborcsardi** [comment]
Should be fixed, please reopen if you still have problems. Thanks!

**Comment by glin** [comment]
Awesome, thanks!

Just one comment - the path separator may not work on Windows: https://github.com/r-lib/callr/commit/29c366cf855194a17062d1ed51c6c7b67387daf8#diff-c9a33000e506e95bca8089aa91efd8b2R34

**Comment by gaborcsardi** [comment]
Good catch! The says it is colon-separated, but of course the docs are different on Windows /o\

https://github.com/wch/r-source/blob/8da74490797aea7a54904d78b0fe1468fbb9e038/src/library/base/man/libPaths.Rd#L52-L80

**Comment by gaborcsardi** [comment]
Hopefully it is good now.
