### ISSUE TITLE
r-lib/processx@feature/restore-std problem

### ISSUE THREAD

**Issue by adigherman** [r-lib/callr#69]
I'm seeing all my Travis CI tests failing after your last commit https://github.com/r-lib/callr/commit/d0e850e7a21660e920141a6b09853e6c03922288. 

<code>Downloading GitHub repo r-lib/processx@feature/restore-std
Error in utils::download.file(url, path, method = download_method(), quiet = quiet,  : 
  cannot open URL 'https://api.github.com/repos/r-lib/processx/zipball/feature%2Frestore-std'
Calls: source ... remote_download.github_remote -> download -> base_download</code>

404 it seems. 

@muschellij2

**Comment by gaborcsardi** [comment]
Well, I don't know what you are doing, or where  your tests are, but that branch is gone.

**Comment by gaborcsardi** [comment]
Thanks!
