### ISSUE TITLE
A more humane / concise API for callr::r()

### ISSUE THREAD

**Issue by jennybc** [r-lib/callr#79]
Summarizing a discussion from Slack.

`callr::r()` needs a higher-level API and/or more documentation and examples. Right now, if you take existing guidance (e.g. from the README) and use it naively in some obvious use cases, things get quite clunky.

Collecting good examples and some early thoughts here.

Sometimes you want to apply the `callr::r()` treatment to:

  * A function. Create an adverb?
  * An expression? Or is this just the next bullet point?
  * A script. Is this just #40? 

*Added later: @jimhester points out a connection to the [carrier](https://github.com/r-lib/carrier) package which "creates standalone functions for remote execution".*

> The carrier package provides tools to package up functions so they can be sent to remote R sessions or to different processes, and tools to test your crates locally. They make it easy to control what data should be packaged with the function and what size your crated function is.
>
> Currently carrier only provides a strict function constructor that forces you to be explicit about the functions and the data your function depends on. In the future it will also provide tools to figure it out automatically.

**Comment by jennybc** [comment]
`rmarkdown::render()` is common target for the `callr:r()` treatment, i.e. this is a great way to render a file in a clean process. reprex does this (https://github.com/tidyverse/reprex/blob/8c64e133ac7050bad02151cfb511c138e0a6c30d/R/reprex.R#L384-L395) and I am currently working on an rmarkdown PR to do this inside `rmarkdown::render_site()` (https://github.com/rstudio/rmarkdown/pull/1443).

The history of the rmarkdown PR shows progressively simpler applications of `callr:r()`, in terms of eliminating excessive repetition of the formal arguments to `rmarkdown::render()`. It eventually gets to this point, where `...` is passed around:

``` r
render_new_session <- function(...) {
  if (!requireNamespace("callr", quietly = TRUE)) {
    stop("The callr package must be installed when `new_session: true`.")
  }
  callr::r(
    function(...) { suppressMessages(rmarkdown::render(...)) },
    args = list(...),
    block_callback = function(x) cat(x)
  )
}
```

Question: is this generally a good template? When is it OK to do this? When calling such a function, what must you look out for, e.g. should you always provide arguments in `arg1 = val1` form?

**Comment by jennybc** [comment]
Here's a nice example for exploring the `callr::r()`-ification of `rmarkdown::render()`. If the answer is just "more documentation", perhaps it will be useful.

``` r
lines <- c(
  "#' ---", "#' output: md_document", "#' ---", "",
  "search()", "ls()", "ps::ps_pid(ps::ps_handle())"
)
writeLines(lines, "test.R")

## attach a package, create an object, note the process id
library(stringr)
jenny <- "I was here!"
ps::ps_pid(ps::ps_handle())
#> [1] 32161

## render test document in current session
rmarkdown::render("test.R")
#> processing file: test.spin.Rmd
#> output file: test.knit.md
#> /Applications/RStudio.app/Contents/MacOS/pandoc/pandoc +RTS -K512m -RTS test.utf8.md --to markdown_strict --from markdown+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash --output test.md --standalone
#> 
#> Output created: test.md
cat(readLines("test.md"), sep = "\n")
#>     search()
#>     #>  [1] ".GlobalEnv"        "package:stringr"   "package:stats"    
#>     #>  [4] "package:graphics"  "package:grDevices" "package:utils"    
#>     #>  [7] "package:datasets"  "package:methods"   "Autoloads"        
#>     #> [10] "package:base"
#>     ls()
#>     #> [1] "jenny" "lines"
#>     ps::ps_pid(ps::ps_handle())
#>     #> [1] 32161

## render test document via callr::r(), ie in new session
render_new_session <- function(...) {
  callr::r(
    function(...) { suppressMessages(rmarkdown::render(...)) },
    args = list(...)
  )
}

render_new_session("test.R")
#> [1] "/private/var/folders/vr/gzrbtprx6ybg85y5pvwm1ct40000gn/T/RtmpsaMQDR/reprex15447305cfd7a/test.md"
cat(readLines("test.md"), sep = "\n")
#>     search()
#> 
#>     ## [1] ".GlobalEnv"        "package:stats"     "package:graphics" 
#>     ## [4] "package:grDevices" "package:utils"     "package:datasets" 
#>     ## [7] "package:methods"   "Autoloads"         "package:base"
#> 
#>     ls()
#> 
#>     ## character(0)
#> 
#>     ps::ps_pid(ps::ps_handle())
#> 
#>     ## [1] 32172
```

<sup>Created on 2018-09-13 by the [reprex package](https://reprex.tidyverse.org) (v0.2.0.9000)</sup>

**Comment by jennybc** [comment]
A more radical move would be to offer an adverb, in the spirit of `purrr::safely()`, that could be applied to a function to create a new function that always executes in a fresh session. Here is a small experiment:

``` r
library(rlang)

separately <- function(.f) {
  .f <- as_closure(.f)
  function(...) {
    callr::r(
      new_function(
        args = fn_fmls(.f),
        body = fn_body(.f),
      ),
      args = list(...)
    )
  }
}

g <- function() ps::ps_pid(ps::ps_handle())
g_sep <- separately(g)

g()
#> [1] 33519
separately(g)()
#> [1] 33529
g_sep()
#> [1] 33537
g()
#> [1] 33519
```

Let’s make sure we can still pass arguments.

``` r
h <- function(i = 0) {
  id <- ps::ps_pid(ps::ps_handle())
  setNames(list(id, id + i), c("id",i))
}
h_sep <- separately(h)

h()
#> $id
#> [1] 33519
#> 
#> $`0`
#> [1] 33519
h(2)
#> $id
#> [1] 33519
#> 
#> $`2`
#> [1] 33521
separately(h)(5)
#> $id
#> [1] 33545
#> 
#> $`5`
#> [1] 33550
h_sep(3)
#> $id
#> [1] 33553
#> 
#> $`3`
#> [1] 33556
```

<sup>Created on 2018-09-13 by the [reprex package](https://reprex.tidyverse.org) (v0.2.0.9000)</sup>

Problems pointed out by @hadley and @gaborcsardi:

  * "I would not use rlang just yet, though. rlang is better, but callr is basic infrastructure, and rlang is not strictly needed I think."
  * "It's easy to get something that works for 90% of cases, but getting the last 10% is hard."
  * "I think `separately(dplyr::filter)` would not work" <-- This turned out to be true (see below), although not for the anticipated reason. Non-standard evaluation is probably never going to work with such an adverb.

``` r
library(rlang)

separately <- function(.f) {
  .f <- as_closure(.f)
  function(...) {
    callr::r(
      new_function(
        args = fn_fmls(.f),
        body = fn_body(.f),
      ),
      args = list(...)
    )
  }
}

head(dplyr::filter(iris, Species == "versicolor"), 3)
#>   Sepal.Length Sepal.Width Petal.Length Petal.Width    Species
#> 1          7.0         3.2          4.7         1.4 versicolor
#> 2          6.4         3.2          4.5         1.5 versicolor
#> 3          6.9         3.1          4.9         1.5 versicolor

filter_sep <- separately(dplyr::filter)

filter_sep(iris, Species == "versicolor")
#> Error in as.list.environment(environment()): object 'Species' not found
```

<sup>Created on 2018-09-13 by the [reprex package](https://reprex.tidyverse.org) (v0.2.0.9000)</sup>

**Comment by lionel-** [comment]
The idea with carrier is that interfaces passing functions remote processes would call `as_crate(fn)` on the user input. The default method would pull all global values into a create. It'd also call `rlang::as_function()` so the UI would be:

```r
foo <- "foo"
callr::r(~do(foo))
```

This method is mostly meant for interactive use. It is not robust and might pull too many objects (which is ok but will send too much data to the external process) or not enough (the function won't work as expected, but this should be rare though) into the crate.

To be explicit, create the crate manually by wrapping with `carrier::crate()`:

```r
callr::callr(crate(~pkg::do(!!foo)))      # Inline data by unquoting
callr::callr(crate(~pkg::do(foo), foo))   # Pull data in the crate env
```

In terms of the rmarkdown example, this would become:

```r
render_new_session <- function(...) {
  if (!requireNamespace("callr", quietly = TRUE)) {
    stop("The callr package must be installed when `new_session: true`.")
  }

  callr::r(
    crate(~suppressMessages(rmarkdown::render(!!!list(...)))),
    block_callback = function(x) cat(x)
  )
}
```

It might make sense to allow passing `...` through like `render(...)` instead of `render(!!!list(...))`. Perhaps like this, or is it too magical an UI?

```r
crate(~suppressMessages(rmarkdown::render(...)), ...)
```

This should be just a matter of forcing all dots in `...` to zap their environments and prevent sending too much data to the process, and then binding the dotsxp in the crate env.

Any feedback on the carrier UI is most welcome, it's still a github-only package (though recommended officially in the mlflow package by @javierluraschi and @kevinykuo I believe).


> The ultimate goal should be to use carrier, but for that it needs to go on CRAN and drop the pryr dependency. (pryr brings stringi....)

Right I'll take a look before releasing carrier to CRAN.

**Comment by gaborcsardi** [comment]
OK, so I'll just wait for carrier to be available, and then we can add support for it. 

Btw. this does not even require an API change, because `callr::r()`, `callr::r_bg()` and `callr::r_process` can just take a crate instead function + arguments.

We can still have an adverb, though, even w/o carrier.

**Comment by gaborcsardi** [comment]
I'll close this because it is unlikely that I'll add it. They way callr is used in pak currently, it is not possible to introduce any more dependencies, so carrier or even just rlang is not ok.

If a more humane / concise API is desired, it would have to go in another package.
