### ISSUE TITLE
Issue with the latest stable release (3.1.0) on CRAN

### ISSUE THREAD

**Issue by savingoyal** [r-lib/callr#92]
The following snippet: 

> `install.packages("callr", repos="cran.rstudio.com")`
> `r(function() 1 + "A")`
 
results in -

> Error: lazy-load database '/usr/local/lib/R/site-library/callr/R/callr.rdb' is corrupt
In addition: Warning messages:
1: restarting interrupted promise evaluation
2: internal error -3 in R_decompress1

Restarting my R session takes care of the problem, but I am able to reproduce this issue consistently in a clean R environment. Any pointers around how to avoid this issue? v3.0.0 works perfectly fine.

**Comment by gaborcsardi** [comment]
This is an R bug, and it happens when you install a package that is loaded in the current R session.

**Comment by savingoyal** [comment]
Is there any known workaround?

**Comment by gaborcsardi** [comment]
Btw. I can't reproduce this, what is your OS?

**Comment by savingoyal** [comment]
Ubuntu xenial

**Comment by gaborcsardi** [comment]
As a workaround, you can try running this before the installation:
```
invisible(mget(names(asNamespace("callr")), asNamespace("callr")))
```

**Comment by amarkanday** [comment]
restart R and it should work
