### ISSUE TITLE
callr package  is not getting installed 

### ISSUE THREAD

**Issue by rajsaraiya009** [r-lib/callr#94]

**Comment by gaborcsardi** [comment]
You will have to tell us what you did, and what happened.

**Comment by rajsaraiya009** [comment]
I tried to install devtools then i got the following error, 

Warning: invalid package 'C:\Users\Raj'
Warning: invalid package 'Saraiya\AppData\Local\Temp\RtmpCW46Hs/downloaded_packages/callr_3.1.1.tar.gz'
Error: ERROR: no packages specified
In R CMD INSTALL
Warning in install.packages :
  installation of package ‘callr’ had non-zero exit status
Warning: invalid package 'C:\Users\Raj'
Warning: invalid package 'Saraiya\AppData\Local\Temp\RtmpCW46Hs/downloaded_packages/rcmdcheck_1.3.2.tar.gz'
Error: ERROR: no packages specified
In R CMD INSTALL
Warning in install.packages :
  installation of package ‘rcmdcheck’ had non-zero exit status

which showed callr and rcmdcheck had non-zero exit status, therefore i tried to download callr package and the following error is been shown, 

Warning: invalid package 'C:\Users\Raj'
Warning: invalid package 'Saraiya\AppData\Local\Temp\RtmpCW46Hs/downloaded_packages/callr_3.1.1.tar.gz'
Error: ERROR: no packages specified
In R CMD INSTALL
Warning in install.packages :
  installation of package ‘callr’ had non-zero exit status
can you help me with this ???

**Comment by gaborcsardi** [comment]
You still haven't showed what you did, i.e. the exact commands you ran.

Nevertheless, this is not a callr problem, but probably a base R problem or a problem with your setup.

Also, install callr and other R packages from CRAN:
```
install.packages("callr")
```

**Comment by rajsaraiya009** [comment]
I did try to install by following code, 
install.packages("callr")
and then the error is been shown as above.

**Comment by gaborcsardi** [comment]
Then this is not a callr issue, you probably cannot install package. 

This used to be an issue on older R versions, so if you don't have the latest R 3.5.2, then update to that.

**Comment by rajsaraiya009** [comment]
I just uninstalled R and downloaded the latest version then too it is showing this error

**Comment by gaborcsardi** [comment]
Maybe your system cannot install source packages. Still, this is not a problem with callr, but with R itself or your setup. 

The call zip was built, so it should work now, or soon, depending which mirror you use: https://cran.rstudio.com/web/packages/callr/

**Comment by rajsaraiya009** [comment]
thank you now its working. Appreciated.

**Comment by rajsaraiya009** [comment]
One more request from my side, can i get the link for Rcmdcheck package  1.3.2 cause again for this  it is showing tar.gz  file not zip file. I am having the link (https://cran.r-project.org/web/packages/rcmdcheck/index.html) in which the zip file is of the version 1.3.1 and for me i need 1.3.2 because the tar.gz file being downloaded is of 1.3.2 version.

**Comment by rajsaraiya009** [comment]
@gaborcsardi  can you help me with this ???

**Comment by gaborcsardi** [comment]
CRAN did not build a binary zip for this package, I am not sue why. If you install the source package into a directory without spaces, that should work.
